// frontend/src/app/features/watchlist/watchlist.component.ts
// src/app/features/watchlist/watchlist.component.ts
import { Component, OnInit, HostListener, OnDestroy, ViewChild} from '@angular/core';
import { CommonModule }                 from '@angular/common';
import { FormsModule }                  from '@angular/forms';
import { RouterModule, Router }         from '@angular/router';
import { Observable, Subscription}                   from 'rxjs';

import { WatchlistService } from '../../core/services/watchlist.service';
import { RatingsService }   from '../../core/services/ratings.service';
import { AuthService }      from '../../core/services/auth.service';
import { Content }          from '../../interfaces/content.interface';
import { debugError } from '../../core/utils/logger';
import { FilterService, FilterOptions } from '../../core/services/filter.service';
import { FilterControlsComponent } from '../filter-controls/filter-controls.component';

@Component({
  selector: 'app-watchlist',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, FilterControlsComponent],
  templateUrl: './watchlist.component.html',
  styleUrls: ['./watchlist.component.scss'],
})
export class WatchlistComponent implements OnInit, OnDestroy {
  @ViewChild('ratingInput') ratingInputRef?: any;
  allContents: Content[]           = [];
  filteredContents: Content[]      = [];
  selectedContentId: string | null = null;
  ratingScore                     = '';
  isRatingSubmitted               = false;
  isLoggedIn$: Observable<boolean>;

  currentYear = new Date().getFullYear();
  genres: string[] = [];
  releaseYearMin: number = 1900;
  releaseYearMax: number = this.currentYear;
  imdbRatingMin: number = 0;
  rtRatingMin: number = 0;
  providers: string[] = [];
  showFilters = false;

  private filterServiceSub?: Subscription;

  constructor(
    private watchlistService: WatchlistService,
    private ratingsService:   RatingsService,
    private authService:      AuthService,
    private router:           Router,
    private filterService:    FilterService,
  ) {
    this.isLoggedIn$ = this.authService.isLoggedIn();
  }

  ngOnInit(): void {
    // 1) Lade alle bisherigen User-Ratings
    this.ratingsService.fetchUserRatings().subscribe({
      error: err => debugError('Failed to fetch user ratings', err),
      complete: () => {
        // 2) Dann erst Watchlist laden
        this.loadWatchlist();
      }
    });
    this.filterServiceSub = this.filterService.currentFilters.subscribe(f => {
      this.genres = f.genres;
      this.releaseYearMin = f.releaseYearMin;
      this.releaseYearMax = f.releaseYearMax;
      this.imdbRatingMin = f.imdbRatingMin;
      this.rtRatingMin = f.rtRatingMin;
      this.providers = f.providers;
      this.applyFilters();
    });
  }

  private loadWatchlist(): void {
    this.watchlistService.getWatchlist().subscribe({
      next: data => { this.allContents = data; this.applyFilters(); },
      error: err => debugError('Failed to load watchlist', err),
    });
  }

  removeFromWatchlist(tmdbId: string): void {
    this.watchlistService.removeFromWatchlist(tmdbId).subscribe({
      next: () => {
        this.loadWatchlist();
        this.ratingsService.fetchUserRatings().subscribe();
      },
      error: err => debugError('Failed to remove from watchlist', err),
    });
  }

  startRating(tmdbId: string): void {
    this.isLoggedIn$.subscribe(loggedIn => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      this.selectedContentId = tmdbId;
      this.ratingScore       = '';
      this.isRatingSubmitted = false;
      setTimeout(() => {
        if (this.ratingInputRef && this.ratingInputRef.nativeElement) {
          this.ratingInputRef.nativeElement.focus();
        }
      });
    });
  }

  goToDetail(tmdbId: string) {
    this.router.navigate(['/movies', tmdbId]);
  }

  onCardClick(tmdbId: string) {
    // Wenn gerade ein Rating-Dialog offen ist, nichts tun:
    if (this.selectedContentId) {
      return;
    }
    this.goToDetail(tmdbId);
  }

  stopRating(): void {
    this.selectedContentId = null;
    this.ratingScore       = '';
    this.isRatingSubmitted = false;
  }

  submitRating(tmdbId: string): void {
    const score = parseFloat(this.ratingScore);
    if (isNaN(score) || score < 0 || score > 10) {
      alert('Score must be between 0.0 and 10.0');
      return;
    }
    this.isLoggedIn$.subscribe(loggedIn => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      this.ratingsService.rateContent(tmdbId, score).subscribe({
        next: () => {
          this.isRatingSubmitted = true;
          this.ratingsService.fetchUserRatings().subscribe();
          setTimeout(() => this.stopRating(), 500);
        },
        error: err => debugError('Failed to set rating', err),
      });
    });
  }

  getRating(tmdbId: string): number | null {
    return this.ratingsService.getRating(tmdbId);
  }

  updateFilters(newFilters: Partial<FilterOptions>): void {
    const current = this.filterService.getFilters();
    const updated = { ...current, ...newFilters } as FilterOptions;
    if (newFilters.imdbRatingMin !== undefined) {
      updated.imdbRatingMin = Number(newFilters.imdbRatingMin);
    }
    if (newFilters.rtRatingMin !== undefined) {
      updated.rtRatingMin = Number(newFilters.rtRatingMin);
    }
    if (newFilters.releaseYearMin && updated.releaseYearMax < updated.releaseYearMin) {
      updated.releaseYearMax = updated.releaseYearMin;
    }
    if (newFilters.releaseYearMax && updated.releaseYearMin > updated.releaseYearMax) {
      updated.releaseYearMin = updated.releaseYearMax;
    }

    if (JSON.stringify(current) === JSON.stringify(updated)) {
      return;
    }

    this.filterService.updateFilters(updated);
  }

  resetFilters(): void {
    const defaults: FilterOptions = {
      genres: [],
      releaseYearMin: 1900,
      releaseYearMax: this.currentYear,
      imdbRatingMin: 0,
      rtRatingMin: 0,
      providers: [],
    };

    if (JSON.stringify(this.filterService.getFilters()) === JSON.stringify(defaults)) {
      return;
    }

    this.filterService.resetFilters();
  }

  toggleFilters(): void {
    this.showFilters = !this.showFilters;
  }

  hasActiveFilters(): boolean {
    const f = this.filterService.getFilters();
    return (
      f.genres.length > 0 ||
      f.releaseYearMin !== 1900 ||
      f.releaseYearMax !== this.currentYear ||
      f.imdbRatingMin > 0 ||
      f.rtRatingMin > 0 ||
      f.providers.length > 0
    );
  }

  private applyFilters(): void {
    const f = this.filterService.getFilters();
    this.filteredContents = this.allContents.filter(c => {
      if (f.genres.length > 0 && !(c.genres?.some(g => f.genres.includes(g)))) return false;
      if (f.providers.length > 0 && !(c.providers?.some(p => f.providers.includes(p)))) return false;
      if (c.releaseYear < f.releaseYearMin || c.releaseYear > f.releaseYearMax) return false;
      if (f.imdbRatingMin > 0) {
        if (c.imdbRating == null || c.imdbRating < f.imdbRatingMin) return false;
      }
      if (f.rtRatingMin > 0) {
        if (c.rtRating == null || c.rtRating < f.rtRatingMin) return false;
      }
      return true;
    });
  }

  ngOnDestroy(): void {
    this.filterServiceSub?.unsubscribe();
  }

  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    if (!this.selectedContentId) return;
    if (event.key === 'Escape') return this.stopRating();
    if (event.repeat || event.key === 'Backspace') return;
    event.preventDefault();

    if (/[0-9]/.test(event.key)) {
      if (this.ratingScore === '' || this.ratingScore.endsWith('.')) {
        this.ratingScore += event.key;
      } else {
        this.ratingScore = event.key;
      }
      if (parseFloat(this.ratingScore) > 10) {
        this.ratingScore = '10';
      }
    } else if (event.key === '.') {
      if (!this.ratingScore.includes('.') && this.ratingScore !== '') {
        this.ratingScore += '.';
      }
    } else if (event.key === 'Enter') {
      this.submitRating(this.selectedContentId!);
    }
  }
}

<div class="watchlist-container">
  <div class="watchlist-header-row">
    <h2>My Watchlist</h2>
    <div class="filter-actions">
      <button
        class="filter-toggle-btn"
        [ngClass]="{ 'active': showFilters }"
        (click)="toggleFilters()"
      >
        <svg
          class="filter-icon"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <polygon points="22 3 2 3 10 12.5 10 21 14 21 14 12.5 22 3"></polygon>
        </svg>
        Filter
        <span *ngIf="hasActiveFilters()" class="active-indicator"></span>
      </button>
    </div>
  </div>

  <app-filter-controls
    *ngIf="showFilters"
    [genresSelected]="genres"
    [releaseYearMin]="releaseYearMin"
    [releaseYearMax]="releaseYearMax"
    [imdbRatingMin]="imdbRatingMin"
    [rtRatingMin]="rtRatingMin"
    [providersSelected]="providers"
    [currentYear]="currentYear"
    (filtersChange)="updateFilters($event)"
    (reset)="resetFilters()"
  ></app-filter-controls>
  <div class="content-list">
    <div
      class="content-card"
      *ngFor="let item of filteredContents"
      (mouseleave)="stopRating()"
      (click)="onCardClick(item.tmdbId)"
    >
      <div
        class="card-image"
        [style.backgroundImage]="'url(' + (item.poster || 'https://placehold.co/200x300') + ')'"
      >
        <button
          class="add-btn"
          (click)="removeFromWatchlist(item.tmdbId); $event.stopPropagation()"
        >
          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
            <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
          </svg>
        </button>
        <button class="rating-btn" (click)="startRating(item.tmdbId); $event.stopPropagation()">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
            <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/>
          </svg>
        </button>
        <div class="rating-overlay" *ngIf="selectedContentId === item.tmdbId && !isRatingSubmitted"></div>
        <div class="rating-input-container" *ngIf="selectedContentId === item.tmdbId && !isRatingSubmitted">
          <div class="rating-card">
            <button class="close-btn" (click)="stopRating()">✕</button>
            <h3>Rate “{{ item.title }}”</h3>
            <input
              #ratingInput
              type="text"
              [(ngModel)]="ratingScore"
              placeholder="0.0 – 10.0"
              class="rating-input-field"
              (keydown.enter)="submitRating(item.tmdbId)"
            />
            <button class="submit-rating-btn" (click)="submitRating(item.tmdbId)">
              Submit
            </button>
          </div>
        </div>
        <div class="own-rating-tag" *ngIf="getRating(item.tmdbId) !== null">
          <span class="star-icon">★</span>
          {{ getRating(item.tmdbId) | number:'1.1-1' }}
        </div>
      </div>
      <p class="card-title">{{ item.title }} ({{ item.releaseYear }})</p>
      <div class="ratings-container">
        <div class="imdb-rating">
          <img src="/assets/images/imdb-logo.png" alt="IMDb" class="rating-icon imdb-rating-icon" />
          {{ item.imdbRating != null ? (item.imdbRating | number:'1.1-1') : 'N/A' }}
        </div>
        <div class="rt-rating">
          <img src="/assets/images/rt-logo-cf.png" alt="Rotten Tomatoes" class="rating-icon rt-rating-icon" />
          <ng-container *ngIf="item.rtRating != null; else rtNA">
            {{ item.rtRating | number:'1.0-0' }}%
          </ng-container>
          <ng-template #rtNA>N/A</ng-template>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend/src/features/Watchlist/Watchlist.tsx
import React, { useEffect } from "react";
import { useWatchlist } from "../../hooks/useWatchlist";
import { useRatings } from "../../hooks/useRatings";
import { Link } from "react-router-dom";
import styles from "./Watchlist.module.scss";
import FilterControls from "../FilterControls/FilterControls";

const Watchlist: React.FC = () => {
  const {
    filteredContents,
    filters,
    showFilters,
    toggleFilters,
    hasActiveFilters,
    updateFilters,
    resetFilters,
    removeFromWatchlist,
    startRating,
    stopRating,
    submitRating,
    selectedContentId,
    ratingScore,
    setRatingScore,
    isRatingSubmitted,
  } = useWatchlist();

  const { fetchUserRatings, getRating } = useRatings();

  useEffect(() => {
    fetchUserRatings();
  }, [fetchUserRatings]);

  return (
    <div className={styles.watchlistContainer}>
      <div className={styles.watchlistHeaderRow}>
        <h2>My Watchlist</h2>
        <div className={styles.filterActions}>
          <button
            className={`${styles.filterToggleBtn} ${
              showFilters ? styles.active : ""
            }`}
            onClick={toggleFilters}
          >
            <svg
              className={styles.filterIcon}
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <polygon points="22 3 2 3 10 12.5 10 21 14 21 14 12.5 22 3"></polygon>
            </svg>
            Filter
            {hasActiveFilters() && <span className={styles.activeIndicator}></span>}
          </button>
        </div>
      </div>

      {showFilters && (
        <FilterControls
          genresSelected={filters.genres}
          releaseYearMin={filters.releaseYearMin}
          releaseYearMax={filters.releaseYearMax}
          imdbRatingMin={filters.imdbRatingMin}
          rtRatingMin={filters.rtRatingMin}
          userRatingMin={filters.userRatingMin}
          providersSelected={filters.providers}
          onFiltersChange={updateFilters}
          onReset={resetFilters}
        />
      )}

      <div className={styles.contentList}>
        {filteredContents.map((item) => (
          <Link
            key={item.tmdbId}
            to={`/${item.type === 'tv' ? 'series' : 'movies'}/${item.tmdbId}`}
            className={styles.contentCard}
            onMouseLeave={stopRating}
            onClick={(e) => selectedContentId && e.preventDefault()}
          >
            <div
              className={styles.cardImage}
              style={{
                backgroundImage: `url(${
                  item.poster || "https://placehold.co/200x300"
                })`,
              }}
            >
              <button
                className={styles.addBtn}
                onClick={(e) => {
                  e.preventDefault();
                  removeFromWatchlist(item.tmdbId);
                }}
              >
                <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
                  <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" />
                </svg>
              </button>
              <button
                className={styles.ratingBtn}
                onClick={(e) => {
                  e.preventDefault();
                  startRating(item.tmdbId);
                }}
              >
                <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
                  <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 
                           9.19 8.63 2 9.24l5.46 4.73L5.82 21z" />
                </svg>
              </button>

              {selectedContentId === item.tmdbId && !isRatingSubmitted && (
                <>
                  <div className={styles.ratingOverlay}></div>
                  <div className={styles.ratingInputContainer}>
                    <div className={styles.ratingCard}>
                      <button className={styles.closeBtn} onClick={stopRating}>
                        ✕
                      </button>
                      <h3>Rate “{item.title}”</h3>
                      <input
                        type="text"
                        value={ratingScore}
                        onChange={(e) => setRatingScore(e.target.value)}
                        placeholder="0.0 – 10.0"
                        onKeyDown={(e) =>
                          e.key === "Enter" &&
                          submitRating(item.tmdbId).then(fetchUserRatings)
                        }
                        className={styles.ratingInputField}
                      />
                      <button
                        className={styles.submitRatingBtn}
                        onClick={() =>
                          submitRating(item.tmdbId).then(fetchUserRatings)
                        }
                      >
                        Submit
                      </button>
                    </div>
                  </div>
                </>
              )}

              {getRating(item.tmdbId) !== null && (
                <div className={styles.ownRatingTag}>
                  <span className={styles.starIcon}>★</span>
                  {getRating(item.tmdbId)?.toFixed(1)}
                </div>
              )}
            </div>
            <p className={styles.cardTitle}>
              {item.title} ({item.releaseYear})
            </p>
            <div className={styles.ratingsContainer}>
              <div className={styles.imdbRating}>
                <img
                  src="/assets/images/imdb-logo.png"
                  alt="IMDb"
                  className={styles.ratingIcon}
                />
                {item.imdbRating != null ? item.imdbRating.toFixed(1) : "N/A"}
              </div>
              <div className={styles.rtRating}>
                <img
                  src="/assets/images/rt-logo-cf.png"
                  alt="RT"
                  className={styles.ratingIcon}
                />
                {item.rtRating != null ? `${item.rtRating}%` : "N/A"}
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Watchlist;
