// frontend/src/app/features/series/series.component.ts
import { Component, OnInit, OnDestroy, HostListener, ViewChild} from '@angular/core';
import { CommonModule }                     from '@angular/common';
import { FormsModule }                      from '@angular/forms';
import { RouterModule, Router }             from '@angular/router';
import { Observable, Subject, Subscription, fromEvent } from 'rxjs';
import { debounceTime, distinctUntilChanged, switchMap, take, throttleTime } from 'rxjs/operators';

import { ContentService }    from '../../core/services/content.service';
import { RatingsService }    from '../../core/services/ratings.service';
import { AuthService }       from '../../core/services/auth.service';
import { WatchlistService }  from '../../core/services/watchlist.service';
import { FilterService, FilterOptions } from '../../core/services/filter.service';
import { Content }           from '../../interfaces/content.interface';
import { debugError } from '../../core/utils/logger';
import { FilterControlsComponent } from '../filter-controls/filter-controls.component';

@Component({
  selector: 'app-series',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, FilterControlsComponent],
  templateUrl: './series.component.html',
  styleUrls: ['./series.component.scss'],
})
export class SeriesComponent implements OnInit, OnDestroy  {
  @ViewChild('ratingInput') ratingInputRef?: any;
  series: Content[]                = [];
  selectedContentId: string | null = null;
  ratingScore: string              = '';
  isRatingSubmitted: boolean       = false;
  isLoggedIn$: Observable<boolean>;

  currentPage = 1;
  isLoading = false;
  hasMore = true;
  currentYear = new Date().getFullYear();
  private filterSubject = new Subject<FilterOptions>();
  private filterSub?: Subscription;
  private filterServiceSub?: Subscription;
  private scrollSub?: Subscription;

  private emptyPageCount = 0;
  private readonly maxEmptyPages = 10;
  private readonly maxPageLimit = 50;

  genres: string[] = [];
  releaseYearMin: number = 1900;
  releaseYearMax: number = this.currentYear;
  imdbRatingMin: number = 0;
  rtRatingMin: number = 0;
  providers: string[] = [];

  showFilters = false;

  constructor(
    private contentService: ContentService,
    private ratingsService: RatingsService,
    private authService: AuthService,
    private watchlistService: WatchlistService,
    public filterService: FilterService,
    private router: Router
  ) {
    this.isLoggedIn$ = this.authService.isLoggedIn();
  }

  ngOnInit(): void {
      this.loadPage();
    this.scrollSub = fromEvent(window, 'scroll').pipe(
      throttleTime(200)
    ).subscribe(() => {
      const threshold = 300; // px vor Ende
      const pos = window.innerHeight + window.scrollY;
      const height = document.body.offsetHeight;
      if (height - pos < threshold) this.loadPage();
    });
    this.filterSub = this.filterSubject
      .pipe(
        debounceTime(500),
        distinctUntilChanged((prev, curr) => JSON.stringify(prev) === JSON.stringify(curr)),
        switchMap((filters) => {
          this.currentPage = 1;
          this.emptyPageCount = 0;
          this.hasMore = true;
          this.series = [];
          this.isLoading = true;
          return this.contentService.getFilteredSeries(filters, this.currentPage);
        })
      )
      .subscribe({
        next: (data) => {
          const filtered = data.filter(m => typeof m.imdbRating === 'number');
          this.series = filtered;
          this.currentPage++;
          this.isLoading = false;

          if (filtered.length === 0) {
            this.loadUntilHitOrLimit();
          }
          this.hasMore = true;
        },
        error: () => {
          debugError('Failed to load filtered series');
          this.isLoading = false;
        }
      });

    this.filterServiceSub = this.filterService.currentFilters.subscribe(filters => {
      this.genres = filters.genres;
      this.releaseYearMin = filters.releaseYearMin;
      this.releaseYearMax = filters.releaseYearMax;
      this.imdbRatingMin = filters.imdbRatingMin;
      this.rtRatingMin = filters.rtRatingMin;
      this.providers = filters.providers;
      this.filterSubject.next(filters);
    });
  }

  ngOnDestroy(): void {
    this.filterSub?.unsubscribe();
    this.filterServiceSub?.unsubscribe();
    this.scrollSub?.unsubscribe();
  }

  updateFilters(newFilters: Partial<FilterOptions>): void {
    const currentFilters = this.filterService.getFilters();
    const updatedFilters = { ...currentFilters, ...newFilters } as FilterOptions;
    if (newFilters.imdbRatingMin !== undefined) {
      updatedFilters.imdbRatingMin = Number(newFilters.imdbRatingMin);
    }
    if (newFilters.rtRatingMin !== undefined) {
      updatedFilters.rtRatingMin = Number(newFilters.rtRatingMin);
    }
    if (newFilters.releaseYearMin && updatedFilters.releaseYearMax < updatedFilters.releaseYearMin) {
      updatedFilters.releaseYearMax = updatedFilters.releaseYearMin;
    }
    if (newFilters.releaseYearMax && updatedFilters.releaseYearMin > updatedFilters.releaseYearMax) {
      updatedFilters.releaseYearMin = updatedFilters.releaseYearMax;
    }

    if (JSON.stringify(currentFilters) === JSON.stringify(updatedFilters)) {
      return;
    }

    this.currentPage = 1;
    this.series = [];
    this.hasMore = true;
    this.isLoading = true;
    this.filterService.updateFilters(updatedFilters);
  }

  resetFilters(): void {
    const defaultFilters: FilterOptions = {
      genres: [],
      releaseYearMin: 1900,
      releaseYearMax: this.currentYear,
      imdbRatingMin: 0,
      rtRatingMin: 0,
      providers: [],
    };

    if (JSON.stringify(this.filterService.getFilters()) === JSON.stringify(defaultFilters)) {
      return;
    }

    this.currentPage = 1;
    this.series = [];
    this.hasMore = true;
    this.isLoading = true;
    this.filterService.resetFilters();
  }

  toggleFilters(): void {
    this.showFilters = !this.showFilters;
  }

  hasActiveFilters(): boolean {
    const f = this.filterService.getFilters();
    return (
      f.genres.length > 0 ||
      f.releaseYearMin !== 1900 ||
      f.releaseYearMax !== this.currentYear ||
      f.imdbRatingMin > 0 ||
      f.rtRatingMin > 0 ||
      f.providers.length > 0
    );
  }

  loadUntilHitOrLimit(): void {
    if (this.isLoading || !this.hasMore) return;

    this.isLoading = true;
    const filters = this.filterService.getFilters();

    const tryNextPage = () => {
      this.contentService.getFilteredSeries(filters, this.currentPage).subscribe({
        next: (data) => {
          const filtered = data.filter(m => typeof m.imdbRating === 'number');

          if (filtered.length > 0) {
            this.series.push(...filtered);
            this.emptyPageCount = 0;
          } else {
            this.emptyPageCount++;
          }

          this.currentPage++;

          if (this.emptyPageCount >= this.maxEmptyPages || this.currentPage > this.maxPageLimit) {
            this.hasMore = false;
            this.isLoading = false;
            return;
          }

          if (this.series.length === 0) {
            tryNextPage();
          } else {
            this.isLoading = false;
          }
        },
        error: () => {
          debugError('Fehler beim Vorladen Seite', this.currentPage);
          this.isLoading = false;
        }
      });
    };

    tryNextPage();
  }

  loadSeriesUntil(minCount: number): void {
    if (this.isLoading || !this.hasMore) return;
    this.isLoading = true;

    const filters = this.filterService.getFilters();
    let batchSeries: Content[] = [];

    const tryNext = () => {
      if (this.currentPage > this.maxPageLimit) {
        this.hasMore = false;
        this.isLoading = false;
        return;
      }

      this.contentService.getFilteredSeries(filters, this.currentPage).subscribe({
        next: (data) => {
          const filtered = data.filter(m => typeof m.imdbRating === 'number');

          if (filtered.length > 0) {
            batchSeries.push(...filtered);
            this.emptyPageCount = 0;
          } else {
            this.emptyPageCount++;
          }

          this.currentPage++;

          if (batchSeries.length >= minCount || this.emptyPageCount >= this.maxEmptyPages) {
            this.series.push(...batchSeries);
            this.isLoading = false;
            if (this.emptyPageCount >= this.maxEmptyPages || this.currentPage > this.maxPageLimit) {
              this.hasMore = false;
            }
            return;
          }

          tryNext();
        },
        error: () => {
          debugError('Fehler beim Laden Seite', this.currentPage);
          this.isLoading = false;
        }
      });
    };

    tryNext();
  }

  startRating(tmdbId: string): void {
    this.isLoggedIn$.subscribe((loggedIn: boolean) => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      this.selectedContentId = tmdbId;
      this.ratingScore       = '';
      this.isRatingSubmitted = false;
      setTimeout(() => {
        if (this.ratingInputRef && this.ratingInputRef.nativeElement) {
          this.ratingInputRef.nativeElement.focus();
        }
      });
    });
  }

  stopRating(): void {
    this.selectedContentId = null;
    this.ratingScore       = '';
    this.isRatingSubmitted = false;
  }

  submitRating(tmdbId: string): void {
    const score = parseFloat(this.ratingScore);
    if (isNaN(score) || score < 0 || score > 10) {
      alert('Score must be between 0.0 and 10.0');
      return;
    }
    this.isLoggedIn$.subscribe((loggedIn: boolean) => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      this.ratingsService.rateContent(tmdbId, score).subscribe({
        next: () => {
          this.isRatingSubmitted = true;
          this.ratingsService.fetchUserRatings().subscribe();
          setTimeout(() => this.stopRating(), 500);
        },
        error: err => debugError('Failed to set rating', err),
      });
    });
  }

  isInWatchlist(contentId: string): boolean {
    return this.watchlistService.isInWatchlist(contentId);
  }

  toggleWatchlist(contentId: string): void {
    this.isLoggedIn$.subscribe((loggedIn: boolean) => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      const call = this.isInWatchlist(contentId)
        ? this.watchlistService.removeFromWatchlist(contentId)
        : this.watchlistService.addToWatchlist(contentId, 'tv');

      call.subscribe({
        next: () => {
          // Hier kannst Du optional UI-Updates vornehmen, z.B. lokale Watchlist-IDs neu laden
        },
        error: err => debugError('Watchlist toggle failed', err),
      });
    });
  }

  getRating(tmdbId: string): number | null {
    return this.ratingsService.getRating(tmdbId);
  }

  trackBySeries(index: number, item: Content): string {
    return item.tmdbId;
  }

  goToDetail(tmdbId: string) {
    this.router.navigate(['/series', tmdbId]);
  }
  onCardClick(tmdbId: string) {
    // Wenn gerade ein Rating-Dialog offen ist, nichts tun:
    if (this.selectedContentId) {
      return;
    }
    this.goToDetail(tmdbId);
  }

  loadPage(): void {
    if (this.isLoading || !this.hasMore) return;
    this.isLoading = true;

    this.contentService.getFilteredSeries(this.filterService.getFilters(), this.currentPage).subscribe({
      next: data => {
        const filtered = data.filter(m => typeof m.imdbRating === 'number');

        if (filtered.length > 0) {
          this.series.push(...filtered);
          this.emptyPageCount = 0;
        } else {
          this.emptyPageCount++;
        }

  
        this.currentPage++;
        this.isLoading = false;

        if (this.emptyPageCount >= this.maxEmptyPages) {
          this.hasMore = false;
        }
      },
      error: () => {
        debugError('Failed to load page', this.currentPage);
        this.isLoading = false;
      }
      });
  }

  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    if (!this.selectedContentId) return;
    if (event.key === 'Escape') return this.stopRating();
    if (event.repeat || event.key === 'Backspace') return;
    event.preventDefault();

    if (/[0-9]/.test(event.key)) {
      if (this.ratingScore === '' || this.ratingScore.endsWith('.')) {
        this.ratingScore += event.key;
      } else {
        this.ratingScore = event.key;
      }
      if (parseFloat(this.ratingScore) > 10) {
        this.ratingScore = '10';
      }
    } else if (event.key === '.') {
      if (!this.ratingScore.includes('.') && this.ratingScore !== '') {
        this.ratingScore += '.';
      }
    } else if (event.key === 'Enter') {
      this.submitRating(this.selectedContentId!);
    }
  }
}
<div class="series-container">
  <div class="series-header-row">
    <h2>Series</h2>
    <div class="filter-actions">
      <button
        class="filter-toggle-btn"
        [ngClass]="{ 'active': showFilters }"
        (click)="toggleFilters()"
      >
        <svg
          class="filter-icon"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <polygon points="22 3 2 3 10 12.5 10 21 14 21 14 12.5 22 3"></polygon>
        </svg>
        Filter
        <span *ngIf="hasActiveFilters()" class="active-indicator"></span>
      </button>
    </div>
  </div>

  <app-filter-controls
    *ngIf="showFilters"
    [genresSelected]="genres"
    [releaseYearMin]="releaseYearMin"
    [releaseYearMax]="releaseYearMax"
    [imdbRatingMin]="imdbRatingMin"
    [rtRatingMin]="rtRatingMin"
    [providersSelected]="providers"
    [currentYear]="currentYear"
    (filtersChange)="updateFilters($event)"
    (reset)="resetFilters()"
  ></app-filter-controls>

  <div class="content-list">
    <div
      class="content-card"
      *ngFor="let item of series; trackBy: trackBySeries"
      (mouseleave)="stopRating()"
      (click)="onCardClick(item.tmdbId)"
    >
      <div
        class="card-image"
        [style.backgroundImage]="'url(' + (item.poster || 'https://placehold.co/220x330') + ')'"
      >
        <button
          class="add-btn"
          (click)="toggleWatchlist(item.tmdbId); $event.stopPropagation()"
        >
          <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2">
            <path *ngIf="!isInWatchlist(item.tmdbId)" d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
            <path *ngIf="isInWatchlist(item.tmdbId)" d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" fill="currentColor" stroke="none"/>
          </svg>
        </button>
        <button
          class="rating-btn"
          (click)="startRating(item.tmdbId); $event.stopPropagation()"
        >
          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
            <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/>
          </svg>
        </button>
        <div
          class="rating-overlay"
          *ngIf="selectedContentId === item.tmdbId && !isRatingSubmitted"
        ></div>
        <div
          class="rating-input-container"
          *ngIf="selectedContentId === item.tmdbId && !isRatingSubmitted"
        >
          <div class="rating-card">
            <button class="close-btn" (click)="stopRating()">✕</button>
            <h3>Rate "{{ item.title }}"</h3>
            <input
              #ratingInput
              type="text"
              [(ngModel)]="ratingScore"
              placeholder="0.0 – 10.0"
              class="rating-input-field"
              (keydown.enter)="submitRating(item.tmdbId)"
            />
            <button
              class="submit-rating-btn"
              (click)="submitRating(item.tmdbId)"
            >
              Submit
            </button>
          </div>
        </div>
        <div class="own-rating-tag" *ngIf="getRating(item.tmdbId) !== null">
          <span class="star-icon">★</span>
          {{ getRating(item.tmdbId) | number:'1.1-1' }}
        </div>
      </div>
      <p class="card-title">{{ item.title }} ({{ item.releaseYear }})</p>
      <div class="ratings-container">
        <div class="imdb-rating">
          <img src="/assets/images/imdb-logo.png" alt="IMDb" class="rating-icon imdb-rating-icon" />
          {{ item.imdbRating != null ? (item.imdbRating | number: '1.1-1') : 'N/A' }}
        </div>
        <div class="rt-rating">
          <img src="/assets/images/rt-logo-cf.png" alt="Rotten Tomatoes" class="rating-icon rt-rating-icon" />
          <ng-container *ngIf="item.rtRating != null; else rtNA">{{ item.rtRating | number: '1.0-0' }}%</ng-container>
          <ng-template #rtNA>N/A</ng-template>
        </div>
      </div>
    </div>
  </div>
  <div *ngIf="isLoading" class="loading-indicator">
    <div class="spinner"></div>
    Laden...
  </div>
</div>

// frontend/src/features/Series/Series.tsx
import React, { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useSeries } from "../../hooks/useSeries";
import { useFilters } from "../../hooks/useFilters";
import { useWatchlist } from "../../hooks/useWatchlist";
import { useRatings } from "../../hooks/useRatings";
import FilterControls from "../FilterControls/FilterControls";
import styles from "./Series.module.scss";

const Series: React.FC = () => {
  const navigate = useNavigate();
   const {
    filters,
    updateFilters,
    resetFilters,
    toggleFilters,
    showFilters,
    hasActiveFilters,
  } = useFilters();

  const {
    series,
    fetchNextPage,
    selectedContentId,
    ratingScore,
    setRatingScore,
    isRatingSubmitted,
    isLoading,
    startRating,
    stopRating,
    submitRating,
  } = useSeries(filters);

  const { isInWatchlist, addToWatchlist, removeFromWatchlist } = useWatchlist();
  const { fetchUserRatings, getRating } = useRatings();

  useEffect(() => {
    fetchUserRatings();
  }, [fetchUserRatings]);

  // infinite scroll
  useEffect(() => {
    const handleScroll = () => {
      if (
        window.innerHeight + window.scrollY >=
        document.body.offsetHeight - 300
      ) {
        fetchNextPage();
      }
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [fetchNextPage]);

  return (
    <div className={styles.seriesContainer}>
      <div className={styles.seriesHeaderRow}>
        <h2>Series</h2>
        <div className={styles.filterActions}>
          <button
            className={`${styles.filterToggleBtn} ${
              showFilters ? styles.active : ""
            }`}
            onClick={toggleFilters}
          >
            <svg
              className={styles.filterIcon}
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <polygon points="22 3 2 3 10 12.5 10 21 14 21 14 12.5 22 3"></polygon>
            </svg>
            Filter
            {hasActiveFilters() && (
              <span className={styles.activeIndicator}></span>
            )}
          </button>
        </div>
      </div>

      {showFilters && (
        <FilterControls
          genresSelected={filters.genres}
          releaseYearMin={filters.releaseYearMin}
          releaseYearMax={filters.releaseYearMax}
          imdbRatingMin={filters.imdbRatingMin}
          rtRatingMin={filters.rtRatingMin}
          userRatingMin={filters.userRatingMin}
          providersSelected={filters.providers}
          currentYear={new Date().getFullYear()}
          onFiltersChange={updateFilters}
          onReset={resetFilters}
        />
      )}

      <div className={styles.contentList}>
        {series.map((s) => (
          <div
            key={s.tmdbId}
            className={styles.contentCard}
            onMouseLeave={stopRating}
            onClick={() =>
              !selectedContentId && navigate(`/series/${s.tmdbId}`)
            }
          >
            <div
              className={styles.cardImage}
              style={{
                backgroundImage: `url(${
                  s.poster || "https://placehold.co/220x330"
                })`,
              }}
            >
              {/* Watchlist Button */}
              <button
                className={styles.addBtn}
                onClick={(e) => {
                  e.stopPropagation();
                  isInWatchlist(s.tmdbId)
                    ? removeFromWatchlist(s.tmdbId)
                    : addToWatchlist({ id: s.tmdbId, type: "tv" });
                }}
              >
                <svg
                  viewBox="0 0 24 24"
                  width="20"
                  height="20"
                  fill={isInWatchlist(s.tmdbId) ? "currentColor" : "none"}
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" />
                </svg>
              </button>

              {/* Rating Button */}
              <button
                className={styles.ratingBtn}
                onClick={(e) => {
                  e.stopPropagation();
                  startRating(s.tmdbId);
                }}
              >
                <svg
                  viewBox="0 0 24 24"
                  width="20"
                  height="20"
                  fill="currentColor"
                >
                  <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z" />
                </svg>
              </button>

              {/* Rating Modal */}
              {selectedContentId === s.tmdbId && !isRatingSubmitted && (
                <>
                  <div className={styles.ratingOverlay}></div>
                  <div className={styles.ratingInputContainer}>
                    <div className={styles.ratingCard}>
                      <button
                        className={styles.closeBtn}
                        onClick={stopRating}
                      >
                        ✕
                      </button>
                      <h3>Rate “{s.title}”</h3>
                      <input
                        type="text"
                        value={ratingScore}
                        onChange={(e) => setRatingScore(e.target.value)}
                        placeholder="0.0 – 10.0"
                        className={styles.ratingInputField}
                        onKeyDown={(e) =>
                          e.key === "Enter" &&
                          submitRating(s.tmdbId).then(fetchUserRatings)
                        }
                      />
                      <button
                        className={styles.submitRatingBtn}
                        onClick={() =>
                          submitRating(s.tmdbId).then(fetchUserRatings)
                        }
                      >
                        Submit
                      </button>
                    </div>
                  </div>
                </>
              )}
              {/* Own Rating */}
              {getRating(s.tmdbId) !== null && (
                <div className={styles.ownRatingTag}>
                  <span className={styles.starIcon}>★</span>
                  {getRating(s.tmdbId)?.toFixed(1)}
                </div>
              )}
            </div>
            <p className={styles.cardTitle}>
              {s.title} ({s.releaseYear})
            </p>
            <div className={styles.ratingsContainer}>
              <div className={styles.imdbRating}>
                <img
                  src="/assets/images/imdb-logo.png"
                  alt="IMDb"
                  className={styles.ratingIcon}
                />
                {s.imdbRating != null ? s.imdbRating.toFixed(1) : "N/A"}
              </div>
              <div className={styles.rtRating}>
                <img
                  src="/assets/images/rt-logo-cf.png"
                  alt="RT"
                  className={styles.ratingIcon}
                />
                {s.rtRating != null ? `${s.rtRating}%` : "N/A"}
              </div>
            </div>
          </div>
        ))}
      </div>

      {isLoading && (
        <div className={styles.loadingIndicator}>
          <div className={styles.spinner}></div> Laden...
        </div>
      )}
    </div>
  );
};

export default Series;
