// frontend/src/app/features/movies/movies.component.ts
// movies.component.ts
import {
  Component,
  OnInit,
  OnDestroy,
  HostListener,
  ViewChild
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, Router } from '@angular/router';
import { Observable, Subject, Subscription, fromEvent } from 'rxjs';
import {
  debounceTime,
  distinctUntilChanged,
  switchMap,
  take,
  throttleTime
} from 'rxjs/operators';

import { ContentService } from '../../core/services/content.service';
import { RatingsService } from '../../core/services/ratings.service';
import { AuthService } from '../../core/services/auth.service';
import { WatchlistService } from '../../core/services/watchlist.service';
import { FilterService, FilterOptions } from '../../core/services/filter.service';
import { Content } from '../../interfaces/content.interface';
import { debugError, debugLog } from '../../core/utils/logger';
import { FilterControlsComponent } from '../filter-controls/filter-controls.component';

@Component({
  selector: 'app-movies',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, FilterControlsComponent],
  templateUrl: './movies.component.html',
  styleUrls: ['./movies.component.scss']
})
export class MoviesComponent implements OnInit, OnDestroy {
  @ViewChild('ratingInput') ratingInputRef?: any;
  movies: Content[] = [];
  selectedContentId: string | null = null;
  ratingScore: string = '';
  isRatingSubmitted: boolean = false;
  isLoggedIn$: Observable<boolean>;

  currentPage = 1;
  isLoading = false;
  hasMore = true;
  currentYear = new Date().getFullYear();
  private filterSubject = new Subject<FilterOptions>();
  private filterSub?: Subscription;
  private filterServiceSub?: Subscription;
  private scrollSub?: Subscription;

  private emptyPageCount = 0;
  private readonly maxEmptyPages = 10;
  private readonly maxPageLimit = 50;


  genres: string[] = [];
  releaseYearMin: number = 1900;
  releaseYearMax: number = this.currentYear;
  imdbRatingMin: number = 0;
  rtRatingMin: number = 0;
  providers: string[] = [];

  showFilters = false;

  constructor(
    private contentService: ContentService,
    private ratingsService: RatingsService,
    private authService: AuthService,
    private watchlistService: WatchlistService,
    public filterService: FilterService,
    private router: Router
  ) {
    this.isLoggedIn$ = this.authService.isLoggedIn();
  }

  ngOnInit(): void {
    this.loadPage();
    this.scrollSub = fromEvent(window, 'scroll').pipe(
      throttleTime(200)
    ).subscribe(() => {
      const threshold = 300;
      const pos = window.innerHeight + window.scrollY;
      const height = document.body.offsetHeight;
      if (height - pos < threshold) this.loadPage();
    });
    this.filterSub = this.filterSubject
  .pipe(
    debounceTime(500),
    distinctUntilChanged((prev, curr) => JSON.stringify(prev) === JSON.stringify(curr)),
    switchMap((filters) => {
      this.currentPage = 1;
      this.emptyPageCount = 0;
      this.hasMore = true;
      this.movies = [];
      this.isLoading = true;
      return this.contentService.getFilteredMovies(filters, this.currentPage);
    })
  )
  .subscribe({
    next: (data) => {
      const filtered = data.filter(m => typeof m.imdbRating === 'number');
      this.movies = filtered;
      this.currentPage++;
      this.isLoading = false;

      if (filtered.length === 0) {
        // Starte automatisches Preloading
        this.loadUntilHitOrLimit();
      }
      this.hasMore = true; // lassen wir offen, scroll entscheidet selbst mit emptyPageCount
    },
    error: () => {
      debugError('Failed to load filtered movies');
      this.isLoading = false;
    }
  });


    this.filterServiceSub = this.filterService.currentFilters.subscribe(filters => {
      this.genres = filters.genres;
      this.releaseYearMin = filters.releaseYearMin;
      this.releaseYearMax = filters.releaseYearMax;
      this.imdbRatingMin = filters.imdbRatingMin;
      this.rtRatingMin = filters.rtRatingMin;
      this.providers = filters.providers;
      this.filterSubject.next(filters);
    });
  }

  ngOnDestroy(): void {
    this.filterSub?.unsubscribe();
    this.filterServiceSub?.unsubscribe();
    this.scrollSub?.unsubscribe();
  }

  updateFilters(newFilters: Partial<FilterOptions>): void {
    const currentFilters = this.filterService.getFilters();
    const updatedFilters = { ...currentFilters, ...newFilters } as FilterOptions;
    if (newFilters.imdbRatingMin !== undefined) {
      updatedFilters.imdbRatingMin = Number(newFilters.imdbRatingMin);
    }
    if (newFilters.rtRatingMin !== undefined) {
      updatedFilters.rtRatingMin = Number(newFilters.rtRatingMin);
    }
    if (newFilters.releaseYearMin && updatedFilters.releaseYearMax < updatedFilters.releaseYearMin) {
      updatedFilters.releaseYearMax = updatedFilters.releaseYearMin;
    }
    if (newFilters.releaseYearMax && updatedFilters.releaseYearMin > updatedFilters.releaseYearMax) {
      updatedFilters.releaseYearMin = updatedFilters.releaseYearMax;
    }

    if (JSON.stringify(currentFilters) === JSON.stringify(updatedFilters)) {
      return;
    }

    this.currentPage = 1;
    this.movies = [];
    this.hasMore = true;
    this.isLoading = true;
    this.filterService.updateFilters(updatedFilters);
  }

  resetFilters(): void {
    const defaultFilters: FilterOptions = {
      genres: [],
      releaseYearMin: 1900,
      releaseYearMax: this.currentYear,
      imdbRatingMin: 0,
      rtRatingMin: 0,
      providers: [],
    };

    if (JSON.stringify(this.filterService.getFilters()) === JSON.stringify(defaultFilters)) {
      return;
    }
    
    this.currentPage = 1;
    this.movies = [];
    this.hasMore = true;
    this.isLoading = true;
    this.filterService.resetFilters();
  }

  toggleFilters(): void {
    this.showFilters = !this.showFilters;
  }

  hasActiveFilters(): boolean {
    const f = this.filterService.getFilters();
    return (
      f.genres.length > 0 ||
      f.releaseYearMin !== 1900 ||
      f.releaseYearMax !== this.currentYear ||
      f.imdbRatingMin > 0 ||
      f.rtRatingMin > 0 ||
      f.providers.length > 0
    );
  }

  loadUntilHitOrLimit(): void {
  if (this.isLoading || !this.hasMore) return;

  this.isLoading = true;
  const filters = this.filterService.getFilters();

  const tryNextPage = () => {
    this.contentService.getFilteredMovies(filters, this.currentPage).subscribe({
      next: (data) => {
        const filtered = data.filter(m => typeof m.imdbRating === 'number');

        if (filtered.length > 0) {
          this.movies.push(...filtered);
          this.emptyPageCount = 0;
        } else {
          this.emptyPageCount++;
        }

        this.currentPage++;

        // ⛔ Abbrechen, wenn Grenze erreicht
        if (this.emptyPageCount >= this.maxEmptyPages || this.currentPage > this.maxPageLimit) {
          this.hasMore = false;
          this.isLoading = false;
          return;
        }

        // ✅ Wenn noch keine Treffer → nächste Seite laden
        if (this.movies.length === 0) {
          tryNextPage(); // rekursiv
        } else {
          this.isLoading = false;
        }
      },
      error: () => {
        debugError('Fehler beim Vorladen Seite', this.currentPage);
        this.isLoading = false;
      }
    });
  };

  tryNextPage();
}

  loadMoviesUntil(minCount: number): void {
  if (this.isLoading || !this.hasMore) return;
  this.isLoading = true;

  const filters = this.filterService.getFilters();
  let batchMovies: Content[] = [];

  const tryNext = () => {
    if (this.currentPage > this.maxPageLimit) {
      this.hasMore = false;
      this.isLoading = false;
      return;
    }

    this.contentService.getFilteredMovies(filters, this.currentPage).subscribe({
      next: (data) => {
        const filtered = data.filter(m => typeof m.imdbRating === 'number');

        if (filtered.length > 0) {
          batchMovies.push(...filtered);
          this.emptyPageCount = 0;
        } else {
          this.emptyPageCount++;
        }

        this.currentPage++;

        if (batchMovies.length >= minCount || this.emptyPageCount >= this.maxEmptyPages) {
          this.movies.push(...batchMovies);
          this.isLoading = false;
          if (this.emptyPageCount >= this.maxEmptyPages || this.currentPage > this.maxPageLimit) {
            this.hasMore = false;
          }
          return;
        }

        tryNext(); // nächste Seite
      },
      error: () => {
        debugError('Fehler beim Laden Seite', this.currentPage);
        this.isLoading = false;
      }
    });
  };

  tryNext();
}



  loadPage(): void {
  if (this.isLoading || !this.hasMore) return;
  this.isLoading = true;

  this.contentService.getFilteredMovies(this.filterService.getFilters(), this.currentPage).subscribe({
    next: (data) => {
      const filtered = data.filter(m => typeof m.imdbRating === 'number');

      if (filtered.length > 0) {
        this.movies.push(...filtered);
        this.emptyPageCount = 0; // Reset
      } else {
        this.emptyPageCount++;
      }

      this.currentPage++;
      this.isLoading = false;

      if (this.emptyPageCount >= this.maxEmptyPages) {
        this.hasMore = false;
      }
    },
    error: () => {
      debugError('Fehler beim Laden von Seite', this.currentPage);
      this.isLoading = false;
    }
  });
}


  startRating(tmdbId: string): void {
    this.isLoggedIn$.subscribe((loggedIn: boolean) => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      this.selectedContentId = tmdbId;
      this.ratingScore = '';
      this.isRatingSubmitted = false;
      setTimeout(() => {
        if (this.ratingInputRef && this.ratingInputRef.nativeElement) {
          this.ratingInputRef.nativeElement.focus();
        }
      });
    });
  }

  stopRating(): void {
    this.selectedContentId = null;
    this.ratingScore = '';
    this.isRatingSubmitted = false;
  }

  submitRating(tmdbId: string): void {
    const score = parseFloat(this.ratingScore);
    if (isNaN(score) || score < 0 || score > 10) {
      alert('Bewertung muss zwischen 0.0 und 10.0 liegen');
      return;
    }
    this.isLoggedIn$.pipe(take(1)).subscribe((loggedIn: boolean) => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      this.ratingsService.rateContent(tmdbId, score).subscribe({
        next: () => {
          this.isRatingSubmitted = true;
          this.ratingsService.fetchUserRatings().subscribe();
          setTimeout(() => this.stopRating(), 500);
        },
        error: (err) => debugError('Bewertung fehlgeschlagen', err)
      });
    });
  }

  isInWatchlist(contentId: string): boolean {
    return this.watchlistService.isInWatchlist(contentId);
  }

  toggleWatchlist(contentId: string): void {
    this.isLoggedIn$.pipe(take(1)).subscribe((loggedIn: boolean) => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      const call = this.isInWatchlist(contentId)
        ? this.watchlistService.removeFromWatchlist(contentId)
        : this.watchlistService.addToWatchlist(contentId, 'movie');

      call.subscribe({
        next: () => {},
        error: (err) => debugError('Watchlist-Aktion fehlgeschlagen', err)
      });
    });
  }

  getRating(tmdbId: string): number | null {
    return this.ratingsService.getRating(tmdbId);
  }

  trackByMovie(index: number, movie: Content): string {
    return movie.tmdbId;
  }

  goToDetail(tmdbId: string) {
    this.router.navigate(['/movies', tmdbId]);
  }

  onCardClick(tmdbId: string) {
    if (this.selectedContentId) {
      return;
    }
    this.goToDetail(tmdbId);
  }

  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    if (!this.selectedContentId) return;
    if (event.key === 'Escape') return this.stopRating();
    if (event.repeat || event.key === 'Backspace') return;
    event.preventDefault();

    if (/[0-9]/.test(event.key)) {
      if (this.ratingScore === '' || this.ratingScore.endsWith('.')) {
        this.ratingScore += event.key;
      } else {
        this.ratingScore = event.key;
      }
      if (parseFloat(this.ratingScore) > 10) {
        this.ratingScore = '10';
      }
    } else if (event.key === '.') {
      if (!this.ratingScore.includes('.') && this.ratingScore !== '') {
        this.ratingScore += '.';
      }
    } else if (event.key === 'Enter') {
      this.submitRating(this.selectedContentId!);
    }
  }

}

<div class="movies-container">
  <div class="movies-header-row">
    <h2>Movies</h2>
    <div class="filter-actions">
      <button
        class="filter-toggle-btn"
        [ngClass]="{ 'active': showFilters }"
        (click)="toggleFilters()"
      >
        <svg
          class="filter-icon"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <polygon points="22 3 2 3 10 12.5 10 21 14 21 14 12.5 22 3"></polygon>
        </svg>
        Filter
        <span *ngIf="hasActiveFilters()" class="active-indicator"></span>
      </button>
    </div>
</div>

<app-filter-controls
  *ngIf="showFilters"
  [genresSelected]="genres"
  [releaseYearMin]="releaseYearMin"
  [releaseYearMax]="releaseYearMax"
  [imdbRatingMin]="imdbRatingMin"
  [rtRatingMin]="rtRatingMin"
  [providersSelected]="providers"
  [currentYear]="currentYear"
  (filtersChange)="updateFilters($event)"
  (reset)="resetFilters()"
></app-filter-controls>
  <div class="content-list">
    <div
      class="content-card"
      *ngFor="let item of movies; trackBy: trackByMovie"
      (mouseleave)="stopRating()"
      (click)="onCardClick(item.tmdbId)"
    >
      <div
        class="card-image"
        [style.backgroundImage]="'url(' + (item.poster || 'https://placehold.co/220x330') + ')'"
      >
        <button
          class="add-btn"
          (click)="toggleWatchlist(item.tmdbId); $event.stopPropagation()"
        >
          <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2">
            <path *ngIf="!isInWatchlist(item.tmdbId)" d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
            <path *ngIf="isInWatchlist(item.tmdbId)" d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" fill="currentColor" stroke="none"/>
          </svg>
        </button>
        <button
          class="rating-btn"
          (click)="startRating(item.tmdbId); $event.stopPropagation()"
        >
          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
            <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/>
          </svg>
        </button>
        <div
          class="rating-overlay"
          *ngIf="selectedContentId === item.tmdbId && !isRatingSubmitted"
        ></div>
        <div
          class="rating-input-container"
          *ngIf="selectedContentId === item.tmdbId && !isRatingSubmitted"
        >
          <div class="rating-card">
            <button class="close-btn" (click)="stopRating()">✕</button>
            <h3>Rate "{{ item.title }}"</h3>
            <input
              #ratingInput
              type="text"
              [(ngModel)]="ratingScore"
              placeholder="0.0 – 10.0"
              class="rating-input-field"
              (keydown.enter)="submitRating(item.tmdbId)"
            />
            <button
              class="submit-rating-btn"
              (click)="submitRating(item.tmdbId)"
            >
              Submit
            </button>
          </div>
        </div>
        <div class="own-rating-tag" *ngIf="getRating(item.tmdbId) !== null">
          <span class="star-icon">★</span>
          {{ getRating(item.tmdbId) | number:'1.1-1' }}
        </div>
      </div>
      <p class="card-title">{{ item.title }} ({{ item.releaseYear }})</p>
      <div class="ratings-container">
        <div class="imdb-rating">
          <img src="/assets/images/imdb-logo.png" alt="IMDb" class="rating-icon imdb-rating-icon" />
          {{ item.imdbRating != null ? (item.imdbRating | number: '1.1-1') : 'N/A' }}
        </div>
        <div class="rt-rating">
          <img src="/assets/images/rt-logo-cf.png" alt="Rotten Tomatoes" class="rating-icon rt-rating-icon" />
          <ng-container *ngIf="item.rtRating != null; else rtNA">{{ item.rtRating | number: '1.0-0' }}%</ng-container>
          <ng-template #rtNA>N/A</ng-template>
        </div>
      </div>
    </div>
  </div>
  <div *ngIf="isLoading" class="loading-indicator">
    <div class="spinner"></div>
    Laden...
  </div>
</div>

// frontend/src/features/Movies/Movies.tsx
import React, { useEffect, useState, useCallback } from "react";
import { useMovies } from "../../hooks/useMovies";
import FilterControls from "../FilterControls/FilterControls";
import styles from "./Movies.module.scss";
import { useNavigate } from "react-router-dom";

const Movies: React.FC = () => {
  const {
    movies,
    isLoading,
    hasMore,
    fetchNextPage,
    toggleFilters,
    showFilters,
    filters,
    updateFilters,
    resetFilters,
    hasActiveFilters,
    startRating,
    stopRating,
    submitRating,
    selectedContentId,
    ratingScore,
    setRatingScore,
    isRatingSubmitted,
    toggleWatchlist,
    isInWatchlist,
    getRating,
  } = useMovies();

  const navigate = useNavigate();

  // Infinite Scroll
  useEffect(() => {
    const onScroll = () => {
      if (!hasMore || isLoading) return;
      const threshold = 300;
      const pos = window.innerHeight + window.scrollY;
      const height = document.body.offsetHeight;
      if (height - pos < threshold) {
        fetchNextPage();
      }
    };
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, [hasMore, isLoading, fetchNextPage]);

  const onCardClick = (tmdbId: string) => {
    if (selectedContentId) return;
    navigate(`/movies/${tmdbId}`);
  };

  return (
    <div className={styles.moviesContainer}>
      <div className={styles.moviesHeaderRow}>
        <h2>Movies</h2>
        <div className={styles.filterActions}>
          <button
            className={`${styles.filterToggleBtn} ${
              showFilters ? styles.active : ""
            }`}
            onClick={toggleFilters}
          >
            <svg
              className={styles.filterIcon}
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <polygon points="22 3 2 3 10 12.5 10 21 14 21 14 12.5 22 3"></polygon>
            </svg>
            Filter
            {hasActiveFilters() && (
              <span className={styles.activeIndicator}></span>
            )}
          </button>
        </div>
      </div>

      {showFilters && (
        <FilterControls
          genresSelected={filters.genres}
          releaseYearMin={filters.releaseYearMin}
          releaseYearMax={filters.releaseYearMax}
          imdbRatingMin={filters.imdbRatingMin}
          rtRatingMin={filters.rtRatingMin}
          userRatingMin={filters.userRatingMin}
          providersSelected={filters.providers}

          currentYear={new Date().getFullYear()}
          onFiltersChange={updateFilters}
          onReset={resetFilters}
        />
      )}

      <div className={styles.contentList}>
        {movies.map((item) => (
          <div
            key={item.tmdbId}
            className={styles.contentCard}
            onClick={() => onCardClick(item.tmdbId)}
            onMouseLeave={stopRating}
          >
            <div
              className={styles.cardImage}
              style={{
                backgroundImage: `url(${
                  item.poster || "https://placehold.co/220x330"
                })`,
              }}
            >
              {/* Watchlist */}
              <button
                className={styles.addBtn}
                onClick={(e) => {
                  e.stopPropagation();
                  toggleWatchlist(item.tmdbId);
                }}
              >
                <svg
                  viewBox="0 0 24 24"
                  width="20"
                  height="20"
                  fill={
                    isInWatchlist(item.tmdbId) ? "currentColor" : "none"
                  }
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" />
                </svg>
              </button>

              {/* Rating */}
              <button
                className={styles.ratingBtn}
                onClick={(e) => {
                  e.stopPropagation();
                  startRating(item.tmdbId);
                }}
              >
                <svg
                  viewBox="0 0 24 24"
                  width="20"
                  height="20"
                  fill="currentColor"
                >
                  <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 
                          9.19 8.63 2 9.24l5.46 4.73L5.82 21z" />
                </svg>
              </button>

              {/* Overlay */}
              {selectedContentId === item.tmdbId && !isRatingSubmitted && (
                <>
                  <div className={styles.ratingOverlay}></div>
                  <div className={styles.ratingInputContainer}>
                    <div className={styles.ratingCard}>
                      <button
                        className={styles.closeBtn}
                        onClick={stopRating}
                      >
                        ✕
                      </button>
                      <h3>Rate “{item.title}”</h3>
                      <input
                        type="text"
                        value={ratingScore}
                        onChange={(e) => setRatingScore(e.target.value)}
                        placeholder="0.0 – 10.0"
                        className={styles.ratingInputField}
                        onKeyDown={(e) =>
                          e.key === "Enter" && submitRating(item.tmdbId)
                        }
                      />
                      <button
                        className={styles.submitRatingBtn}
                        onClick={() => submitRating(item.tmdbId)}
                      >
                        Submit
                      </button>
                    </div>
                  </div>
                </>
              )}

              {/* Eigene Bewertung */}
              {getRating(item.tmdbId) !== null && (
                <div className={styles.ownRatingTag}>
                  <span className={styles.starIcon}>★</span>
                  {getRating(item.tmdbId)?.toFixed(1)}
                </div>
              )}
            </div>
            <p className={styles.cardTitle}>
              {item.title} ({item.releaseYear})
            </p>
            <div className={styles.ratingsContainer}>
              <div className={styles.imdbRating}>
                <img
                  src="/assets/images/imdb-logo.png"
                  alt="IMDb"
                  className={`${styles.ratingIcon} ${styles.imdbRatingIcon}`}
                />
                {item.imdbRating != null ? item.imdbRating.toFixed(1) : "N/A"}
              </div>
              <div className={styles.rtRating}>
                <img
                  src="/assets/images/rt-logo-cf.png"
                  alt="Rotten Tomatoes"
                  className={`${styles.ratingIcon} ${styles.rtRatingIcon}`}
                />
                {item.rtRating != null ? `${item.rtRating}%` : "N/A"}
              </div>
            </div>
          </div>
        ))}
      </div>

      {isLoading && (
        <div className={styles.loadingIndicator}>
          <div className={styles.spinner}></div>
          Laden…
        </div>
      )}
    </div>
  );
};

export default Movies;
