// frontend/src/app/features/movie-detail/movie-detail.component.ts
import { Component, OnInit }        from '@angular/core';
import { CommonModule }             from '@angular/common';
import { FormsModule }              from '@angular/forms';
import { ActivatedRoute, Router }   from '@angular/router';
import { ContentService }           from '../../core/services/content.service';
import { WatchlistService }         from '../../core/services/watchlist.service';
import { RatingsService }           from '../../core/services/ratings.service';
import { AuthService }              from '../../core/services/auth.service';
import { Content }                  from '../../interfaces/content.interface';
import { providerLogoMap }          from '../../shared/provider-logos';
import { debugError } from '../../core/utils/logger';

@Component({
  standalone: true,
  selector: 'app-movie-detail',
  imports: [CommonModule, FormsModule],
  templateUrl: './movie-detail.component.html',
  styleUrls: ['./movie-detail.component.scss']
})
export class MovieDetailComponent implements OnInit {
  movie: Content | null         = null;
  isLoading                     = true;
  isInWL                        = false;

  // Rate‐Overlay
  selectedContentId: string | null = null;
  ratingScore            = '';
  isRatingSubmitted      = false;

  // Eigenes Rating
  userRating: number | null = null;

  readonly providerLogoMap = providerLogoMap;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private contentService: ContentService,
    private watchlist: WatchlistService,
    private ratings: RatingsService,
    private auth: AuthService
  ) {}

  ngOnInit() {
    const tmdbId = this.route.snapshot.paramMap.get('id')!;
    this.contentService.getMovieDetails(tmdbId).subscribe({
      next: m => {
        this.movie     = m;
        this.isLoading = false;
        // Watchlist‐Cache laden
        this.watchlist.getWatchlist().subscribe(list =>
          this.isInWL = list.some(c => c.tmdbId === tmdbId)
        );
        // Rating‐Cache laden
        this.ratings.fetchUserRatings().subscribe(() =>
          this.userRating = this.ratings.getRating(tmdbId)
        );
      },
      error: () => this.isLoading = false
    });
  }

  toggleWatchlist() {
    this.auth.isLoggedIn().subscribe(loggedIn => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      if (!this.movie) return;
      const id = this.movie.tmdbId;
      const op = this.isInWL
        ? this.watchlist.removeFromWatchlist(id)
        : this.watchlist.addToWatchlist(id, 'movie');
      op.subscribe({
        next: res => {
          if (res !== null && res !== undefined) {
            this.isInWL = !this.isInWL;
          }
        },
        error: err => debugError('Failed to toggle watchlist', err)
      });
    });
  }

  onClickRateButton() {
    this.auth.isLoggedIn().subscribe(loggedIn => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
      } else if (this.movie) {
        this.selectedContentId = this.movie.tmdbId;
        this.ratingScore      = '';
        this.isRatingSubmitted = false;
      }
    });
  }

  submitRating() {
    if (!this.movie) return;
    const score = parseFloat(this.ratingScore);
    if (isNaN(score) || score < 0 || score > 10) {
      alert('Score must be between 0.0 and 10.0');
      return;
    }
    this.ratings.rateContent(this.movie.tmdbId, score).subscribe({
      next: () => {
        this.isRatingSubmitted = true;
        this.ratings.fetchUserRatings().subscribe(() =>
          this.userRating = this.ratings.getRating(this.movie!.tmdbId)
        );
        setTimeout(() => this.selectedContentId = null, 500);
      },
      error: err => debugError('Failed to set rating', err)
    });
  }

  cancelRating() {
    this.selectedContentId = null;
    this.ratingScore      = '';
    this.isRatingSubmitted = false;
  }

  getKnownProviders(providers: string[] | undefined): string[] {
    return (providers || []).filter(p => this.providerLogoMap[p]);
  }

  getProviderLogoPath(provider: string): string | null {
    const file = this.providerLogoMap[provider];
    return file ? '/assets/images/providers/' + file : null;
  }
}

<ng-container *ngIf="isLoading">
  <div class="loader">Lade …</div>
</ng-container>

<ng-container *ngIf="!isLoading && movie; else noMovie">
  <div class="movie-detail-container">

    <header class="movie-header">
      <h1 class="movie-title">
        {{ movie.title }}
        <span class="movie-year">({{ movie.releaseYear }})</span>
      </h1>
    </header>

    <div class="movie-content">
      <div class="poster-wrapper">
        <!-- Add-Button oben links -->
        <button class="add-btn" (click)="toggleWatchlist(); $event.stopPropagation()">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2">
            <path *ngIf="!isInWL" d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
            <path *ngIf="isInWL" d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" fill="currentColor" stroke="none"/>
          </svg>
        </button>

        <!-- Rate-Button direkt darunter -->
        <button class="rating-btn" (click)="onClickRateButton(); $event.stopPropagation()">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
            <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2
                     9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/>
          </svg>
        </button>

        <img
          [src]="movie.poster || 'https://placehold.co/200x300'"
          [alt]="movie.title"
          class="movie-poster"
        />

        <!-- Rating-Overlay -->
        <div
          class="rating-overlay"
          *ngIf="selectedContentId === movie.tmdbId && !isRatingSubmitted"
          (click)="cancelRating()"
        ></div>

        <!-- Rating-Card -->
        <div
          class="rating-input-container"
          *ngIf="selectedContentId === movie.tmdbId && !isRatingSubmitted"
          (mouseleave)="cancelRating()"
        >
          <div class="rating-card">
            <button class="close-btn" (click)="cancelRating()">✕</button>
            <h3>Rate “{{ movie.title }}”</h3>
            <input
              #ratingInput
              type="text"
              [(ngModel)]="ratingScore"
              placeholder="0.0 – 10.0"
              (keydown.enter)="submitRating()"
              class="rating-input-field"
            />
            <button class="submit-rating-btn" (click)="submitRating()">
              Submit
            </button>
          </div>
        </div>
      </div>

      <div class="details-wrapper">
        <!-- External Ratings -->
        <div class="ratings-wrapper">
        <div class="rating-block">
          <img
            src="/assets/images/imdb-logo.png"
            alt="IMDb"
            class="rating-icon imdb-rating-icon"
          />
          <span class="rating-value">
            {{ movie.imdbRating != null
                ? (movie.imdbRating | number:'1.1-1')
                : '–' }}
          </span>
        </div>
        <div class="rating-block">
          <img
            src="/assets/images/rt-logo-cf.png"
            alt="Rotten Tomatoes"
            class="rating-icon rt-rating-icon"
          />
          <span class="rating-value">
            {{ movie.rtRating != null
                ? (movie.rtRating + '%')
                : '–' }}
          </span>
        </div>
        <div class="own-rating-tag" *ngIf="userRating != null">
          <span class="star-icon">★</span>
          {{ userRating | number:'1.1-1' }}
        </div>
        </div>

        <!-- Genres -->
        <div class="genres">
          <span class="genre-pill" *ngFor="let g of (movie.genres || [])">
            {{ g }}
          </span>
        </div>

        <section class="providers" *ngIf="getKnownProviders(movie.providers).length">
          <ng-container *ngFor="let p of getKnownProviders(movie.providers)">
            <img
              *ngIf="getProviderLogoPath(p) as logo"
              [src]="logo"
              [alt]="p"
              class="provider-logo"
            />
          </ng-container>
        </section>


        <!-- Overview -->
        <section class="overview">
          <h2>Handlung</h2>
          <p>{{ movie.overview || 'Keine Beschreibung vorhanden.' }}</p>
        </section>

        <!-- Cast -->
        <section class="cast-section" *ngIf="(movie.cast || []).length > 0">
          <h2>Hauptbesetzung</h2>
          <div class="cast-list">
            <div class="cast-item" *ngFor="let actor of (movie.cast || [])">
              <div class="cast-image-wrapper">
                <img
                  [src]="actor.profilePathUrl"
                  [alt]="actor.name"
                />
              </div>
              <div class="cast-info">
                <span class="cast-name">{{ actor.name }}</span>
                <span class="cast-char">{{ actor.character }}</span>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</ng-container>

<ng-template #noMovie>
  <div class="loader">Film nicht gefunden.</div>
</ng-template>

// frontend/src/features/MovieDetail/MovieDetail.tsx
import React, { useState } from "react";
import { useParams } from "react-router-dom";
import { useMovieDetail } from "../../hooks/useMovieDetail";
import styles from "./MovieDetail.module.scss";
import { providerLogoMap } from "../../constants/providers";

const MovieDetail: React.FC = () => {
  const { id } = useParams();
  const {
    movie,
    isLoading,
    isInWL,
    userRating,
    toggleWatchlist,
    submitRating,
  } = useMovieDetail(id);

  // UI-States für Rating-Overlay
  const [selectedContentId, setSelectedContentId] = useState<string | null>(null);
  const [ratingScore, setRatingScore] = useState("");
  const [isRatingSubmitted, setIsRatingSubmitted] = useState(false);

  if (isLoading) return <div className={styles.loader}>Lade …</div>;
  if (!movie) return <div className={styles.loader}>Film nicht gefunden.</div>;

  const getKnownProviders = (providers?: string[]) =>
    (providers || []).filter((p) => providerLogoMap[p]);

  const getProviderLogoPath = (provider: string) =>
    providerLogoMap[provider]
      ? `/assets/images/providers/${providerLogoMap[provider]}`
      : null;

  const handleRateClick = () => {
    setSelectedContentId(movie.tmdbId);
    setRatingScore("");
    setIsRatingSubmitted(false);
  };

  const handleSubmitRating = async () => {
    const score = parseFloat(ratingScore);
    if (isNaN(score) || score < 0 || score > 10) {
      alert("Score must be between 0.0 and 10.0");
      return;
    }
    await submitRating(score);
    setIsRatingSubmitted(true);
    setTimeout(() => setSelectedContentId(null), 500);
  };

  const cancelRating = () => {
    setSelectedContentId(null);
    setRatingScore("");
    setIsRatingSubmitted(false);
  };

  return (
    <div className={styles.movieDetailContainer}>
      <header className={styles.movieHeader}>
        <h1 className={styles.movieTitle}>
          {movie.title}
          {movie.releaseYear && (
            <span className={styles.movieYear}>({movie.releaseYear})</span>
          )}
        </h1>
      </header>

      <div className={styles.movieContent}>
        <div className={styles.posterWrapper}>
          {/* Watchlist-Button */}
          <button
            className={styles.addBtn}
            onClick={(e) => {
              e.stopPropagation();
              toggleWatchlist();
            }}
          >
            <svg
              viewBox="0 0 24 24"
              width="20"
              height="20"
              fill={isInWL ? "currentColor" : "none"}
              stroke="currentColor"
              strokeWidth="2"
            >
              <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" />
            </svg>
          </button>

          {/* Rating-Button */}
          <button
            className={styles.ratingBtn}
            onClick={(e) => {
              e.stopPropagation();
              handleRateClick();
            }}
          >
            <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
              <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 
                      9.19 8.63 2 9.24l5.46 4.73L5.82 21z" />
            </svg>
          </button>

          <img
            src={movie.poster || "https://placehold.co/200x300"}
            alt={movie.title}
            className={styles.moviePoster}
          />

          {/* Rating Overlay + Eingabe */}
          {selectedContentId === movie.tmdbId && !isRatingSubmitted && (
            <>
              <div className={styles.ratingOverlay} onClick={cancelRating}></div>
              <div
                className={styles.ratingInputContainer}
                onMouseLeave={cancelRating}
              >
                <div className={styles.ratingCard}>
                  <button className={styles.closeBtn} onClick={cancelRating}>
                    ✕
                  </button>
                  <h3>Rate “{movie.title}”</h3>
                  <input
                    type="text"
                    value={ratingScore}
                    onChange={(e) => setRatingScore(e.target.value)}
                    placeholder="0.0 – 10.0"
                    className={styles.ratingInputField}
                    onKeyDown={(e) => e.key === "Enter" && handleSubmitRating()}
                  />
                  <button
                    className={styles.submitRatingBtn}
                    onClick={handleSubmitRating}
                  >
                    Submit
                  </button>
                </div>
              </div>
            </>
          )}
        </div>

        <div className={styles.detailsWrapper}>
          {/* Ratings */}
          <div className={styles.ratingsWrapper}>
            <div className={styles.ratingBlock}>
              <img
                src="/assets/images/imdb-logo.png"
                alt="IMDb"
                className={`${styles.ratingIcon} ${styles.imdbRatingIcon}`}
              />
              <span className={styles.ratingValue}>
                {movie.imdbRating != null ? movie.imdbRating.toFixed(1) : "–"}
              </span>
            </div>
            <div className={styles.ratingBlock}>
              <img
                src="/assets/images/rt-logo-cf.png"
                alt="Rotten Tomatoes"
                className={`${styles.ratingIcon} ${styles.rtRatingIcon}`}
              />
              <span className={styles.ratingValue}>
                {movie.rtRating != null ? `${movie.rtRating}%` : "–"}
              </span>
            </div>
            {userRating != null && (
              <div className={styles.ownRatingTag}>
                <span className={styles.starIcon}>★</span>
                {userRating.toFixed(1)}
              </div>
            )}
          </div>

          {/* Genres */}
          {movie.genres && movie.genres.length > 0 && (
            <div className={styles.genres}>
              {movie.genres.map((g) => (
                <span key={g} className={styles.genrePill}>
                  {g}
                </span>
              ))}
            </div>
          )}

          {/* Providers */}
          {getKnownProviders(movie.providers).length > 0 && (
            <section className={styles.providers}>
              {getKnownProviders(movie.providers).map((p) => {
                const logo = getProviderLogoPath(p);
                return (
                  logo && (
                    <img
                      key={p}
                      src={logo}
                      alt={p}
                      className={styles.providerLogo}
                    />
                  )
                );
              })}
            </section>
          )}

          {/* Overview */}
          <section className={styles.overview}>
            <h2>Handlung</h2>
            <p>{movie.overview || "Keine Beschreibung vorhanden."}</p>
          </section>

          {/* Cast */}
          {movie.cast && movie.cast.length > 0 && (
            <section className={styles.castSection}>
              <h2>Hauptbesetzung</h2>
              <div className={styles.castList}>
                {movie.cast.map((actor) => (
                  <div key={actor.name} className={styles.castItem}>
                    <div className={styles.castImageWrapper}>
                      <img src={actor.profilePathUrl} alt={actor.name} />
                    </div>
                    <div className={styles.castInfo}>
                      <span className={styles.castName}>{actor.name}</span>
                      <span className={styles.castChar}>{actor.character}</span>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}
        </div>
      </div>
    </div>
  );
};

export default MovieDetail;
