// frontend/src/app/home/home.component.ts
// src/app/home/home.component.ts
import { Component, OnInit, OnDestroy} from '@angular/core';
import { ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { Observable, Subscription } from 'rxjs';
import { take } from 'rxjs/operators';

import { ContentService } from '../core/services/content.service';
import { WatchlistService } from '../core/services/watchlist.service';
import { RatingsService } from '../core/services/ratings.service';
import { AuthService } from '../core/services/auth.service';
import { Content } from '../interfaces/content.interface';
import { debugError } from '../core/utils/logger';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

interface Category {
  id: string;
  title: string;
  items: Content[];
  isLoading: boolean;
}
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
})
export class HomeComponent implements OnInit, OnDestroy {
  // Reference to the rating input field
  @ViewChild('ratingInput') ratingInputRef?: any;
  /** Gibt true zurück, wenn der Slider nach rechts gescrollt werden kann */
  canScrollRight(categoryId: string): boolean {
    const el = document.getElementById(categoryId);
    if (!el) return false;
    // Allow right scroll only if content is wider than container and not at the end
    return el.scrollWidth - el.clientWidth - el.scrollLeft > 10;
  }
  /** Speichert für jede Kategorie, ob nach links gescrollt werden kann */
  scrollLeftState: { [key: string]: boolean } = {};

  /** Gibt true zurück, wenn der Slider nach links gescrollt werden kann */
  canScrollLeft(categoryId: string): boolean {
    return !!this.scrollLeftState[categoryId];
  }
  categories: Category[] = [
    { id: 'trending',    title: 'Trending Now',  items: [], isLoading: false },
    { id: 'top-rated',   title: 'Top Rated',     items: [], isLoading: false },
    { id: 'new-releases',title: 'New Releases',  items: [], isLoading: false },
    { id: 'watchlist',   title: 'My Watchlist',  items: [], isLoading: false },
  ];

  placeholderItems = Array.from({ length: 5 });

  private setLoading(index: number, value: boolean): void {
    if (this.categories[index]) {
      this.categories[index].isLoading = value;
    }
  }

  isLoggedIn$: Observable<boolean>;
  selectedContentId: string | null = null;
  selectedCategoryId: string | null = null;
  ratingScore = '';
  isRatingSubmitted = false;

  private loginSub?: Subscription;

  constructor(
    private contentService: ContentService,
    private watchlistService: WatchlistService,
    private ratingsService: RatingsService,
    private authService: AuthService,
    private router: Router
  ) {
    this.isLoggedIn$ = this.authService.isLoggedIn();
  }

  ngOnInit(): void {
    // zuerst alle User-Ratings laden
    this.ratingsService.fetchUserRatings().subscribe({
      error: err => debugError('Failed to fetch user ratings', err)
    });

    // dann Kategorien laden
    this.loginSub = this.isLoggedIn$.subscribe(loggedIn => {
      if (loggedIn) {
        this.loadCategories();
      } else {
        this.loadPublicCategories();
      }
    });
  }

  private loadCategories(): void {
    this.setLoading(0, true);
    this.contentService.getTrending().subscribe({
      next: data => {
        this.categories[0].items = data;
        this.setLoading(0, false);
        setTimeout(() => this.updateScrollState(this.categories[0].id));
      },
      error: err => { debugError('Failed to load trending', err); this.setLoading(0, false); },
    });
    this.setLoading(1, true);
    this.contentService.getTopRated().subscribe({
      next: data => {
        this.categories[1].items = data;
        this.setLoading(1, false);
        setTimeout(() => this.updateScrollState(this.categories[1].id));
      },
      error: err => { debugError('Failed to load top rated', err); this.setLoading(1, false); },
    });
    this.setLoading(2, true);
    this.contentService.getNewReleases().subscribe({
      next: data => {
        this.categories[2].items = data;
        this.setLoading(2, false);
        setTimeout(() => this.updateScrollState(this.categories[2].id));
      },
      error: err => { debugError('Failed to load new releases', err); this.setLoading(2, false); },
    });
    this.setLoading(3, true);
    this.watchlistService.getWatchlist().subscribe({
      next: data => {
        this.categories[3].items = data;
        this.setLoading(3, false);
        setTimeout(() => this.updateScrollState(this.categories[3].id));
      },
      error: err => { debugError('Failed to load watchlist', err); this.setLoading(3, false); },
    });
  }

  private loadPublicCategories(): void {
    this.setLoading(0, true);
    this.contentService.getTrending().subscribe({
      next: data => {
        this.categories[0].items = data;
        this.setLoading(0, false);
        setTimeout(() => this.updateScrollState(this.categories[0].id));
      },
      error: err => { debugError('Failed to load trending', err); this.setLoading(0, false); },
    });
    this.setLoading(1, true);
    this.contentService.getTopRated().subscribe({
      next: data => {
        this.categories[1].items = data;
        this.setLoading(1, false);
        setTimeout(() => this.updateScrollState(this.categories[1].id));
      },
      error: err => { debugError('Failed to load top rated', err); this.setLoading(1, false); },
    });
    this.setLoading(2, true);
    this.contentService.getNewReleases().subscribe({
      next: data => {
        this.categories[2].items = data;
        this.setLoading(2, false);
        setTimeout(() => this.updateScrollState(this.categories[2].id));
      },
      error: err => { debugError('Failed to load new releases', err); this.setLoading(2, false); },
    });
  }

   // in src/app/home/home.component.ts

/** externes Rating (IMDb/RT) */
getExternalRating(item: Content, source: 'imdb' | 'rt'): number | null {
  if (source === 'imdb') {
    return item.imdbRating ?? null;
  } else {
    return item.rtRating  ?? null;
  }
}


  /** eigenes Rating aus RatingsService (float 1.1-1) */
  getRating(tmdbId: string): number | null {
    return this.ratingsService.getRating(tmdbId);
  }

  isInWatchlist(contentId: string): boolean {
    return this.watchlistService.isInWatchlist(contentId);
  }

  toggleWatchlist(contentId: string, type: 'movie' | 'tv'): void {
    this.isLoggedIn$.pipe(take(1)).subscribe(loggedIn => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      const call = this.isInWatchlist(contentId)
        ? this.watchlistService.removeFromWatchlist(contentId)
        : this.watchlistService.addToWatchlist(contentId, type);

      call.subscribe({
        next: () => this.loadCategories(),
        error: err => debugError(err)
      });
    });
  }

  startRating(categoryId: string, contentId: string): void {
    this.isLoggedIn$.pipe(take(1)).subscribe(loggedIn => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      this.selectedCategoryId = categoryId;
      this.selectedContentId = contentId;
      this.ratingScore = '';
      this.isRatingSubmitted = false;
      setTimeout(() => {
        if (this.ratingInputRef && this.ratingInputRef.nativeElement) {
          this.ratingInputRef.nativeElement.focus();
        }
      });
    });
  }

  stopRating(): void {
    this.selectedCategoryId = null;
    this.selectedContentId = null;
    this.ratingScore = '';
    this.isRatingSubmitted = false;
  }

  submitRating(tmdbId: string): void {
    const score = parseFloat(this.ratingScore);
    if (isNaN(score) || score < 0 || score > 10) {
      debugError('Invalid rating: must be between 0.0 and 10.0');
      return;
    }
    this.isLoggedIn$.pipe(take(1)).subscribe(loggedIn => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      // RATE VIA RatingsService
      this.ratingsService.rateContent(tmdbId, score).subscribe({
        next: () => {
          this.isRatingSubmitted = true;
          // neu laden, damit Badge angezeigt wird
          this.ratingsService.fetchUserRatings().subscribe();
          setTimeout(() => this.stopRating(), 500);
        },
        error: err => debugError('Failed to set rating', err)
      });
    });
  }

  scrollLeft(categoryId: string): void {
    const el = document.getElementById(categoryId);
    if (el) {
      el.scrollBy({ left: -300, behavior: 'smooth' });
      setTimeout(() => this.updateScrollState(categoryId), 350);
    }
  }

  scrollRight(categoryId: string): void {
    const el = document.getElementById(categoryId);
    if (el) {
      el.scrollBy({ left: 300, behavior: 'smooth' });
      setTimeout(() => this.updateScrollState(categoryId), 350);
    }
  }

  /** Prüft nach jedem Scrollen, ob links gescrollt werden kann */
  updateScrollState(categoryId: string): void {
    const el = document.getElementById(categoryId);
    this.scrollLeftState[categoryId] = !!el && el.scrollLeft > 0;
  }

  /** Initialisiere Scroll-Status nach View-Init */
  ngAfterViewInit(): void {
    this.categories.forEach(cat => this.updateScrollState(cat.id));
  }

  goToDetail(tmdbId: string) {
    this.router.navigate(['/movies', tmdbId]);
  }

  onCardClick(tmdbId: string) {
    // Wenn gerade ein Rating-Dialog offen ist, nichts tun:
    if (this.selectedContentId) {
      return;
    }
    this.goToDetail(tmdbId);
  }

  ngOnDestroy(): void {
    this.loginSub?.unsubscribe();
  }

  navigateTo(item: any) {
  const route = item.type === 'movie' ? '/movies' : '/series';
  this.router.navigate([route, item.tmdbId]);
}
}

<div class="home-container">

  <!-- Hero Section -->
  <section class="hero-section">
    <div class="hero-content">
      <h1>Your personal streaming companion</h1>
      <p>rate, discover and keep track of what you love</p>
    </div>
  </section>

  <!-- Category Sections -->
  <section class="category-section" *ngFor="let category of categories">
    <h2>{{ category.title }}</h2>
    <div class="slider-container">
      <button
        class="slider-arrow left-arrow"
        *ngIf="canScrollLeft(category.id)"
        (click)="scrollLeft(category.id)"
      >
        <svg viewBox="0 0 24 24" width="32" height="32" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            d="M15.5 19.5L8.5 12.5L15.5 5.5"
            stroke="#fff"
            stroke-width="2.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </button>

      <div class="scroll-container" [id]="category.id">
        <div class="content-list">

          <!-- Zeige Content-Cards oder Ladeplatzhalter -->
          <ng-container *ngIf="category.items.length > 0; else loadingState">
            <div
              class="content-card"
              *ngFor="let item of category.items"
              (click)="onCardClick(item.tmdbId)"
              (mouseleave)="stopRating()"
            >
              <!-- Poster + Add/Rate Buttons -->
              <div
                class="card-image"
                [style.backgroundImage]="'url(' + (item.poster || 'https://placehold.co/200x300') + ')'"
              >
                <button
                  class="add-btn"
                  (click)="toggleWatchlist(item.tmdbId, item.type); $event.stopPropagation()"
                >
                  <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2">
                    <path
                      *ngIf="!isInWatchlist(item.tmdbId)"
                      d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"
                    />
                    <path
                      *ngIf="isInWatchlist(item.tmdbId)"
                      d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"
                      fill="currentColor"
                      stroke="none"
                    />
                  </svg>
                </button>
                <button
                  class="rating-btn"
                  (click)="startRating(category.id, item.tmdbId); $event.stopPropagation()"
                >
                  <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
                    <path
                      d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2
                         9.19 8.63 2 9.24l5.46 4.73L5.82 21z"
                    />
                  </svg>
                </button>

                <!-- Rating Overlay & Eingabemaske -->
                <div
                  class="rating-overlay"
                  *ngIf="selectedCategoryId === category.id && selectedContentId === item.tmdbId && !isRatingSubmitted"
                ></div>
                <div
                  class="rating-input-container"
                  *ngIf="selectedCategoryId === category.id && selectedContentId === item.tmdbId && !isRatingSubmitted"
                >
                  <div class="rating-card">
                    <button class="close-btn" (click)="stopRating()">✕</button>
                    <h3>Rate “{{ item.title }}”</h3>
                    <input
                      #ratingInput
                      type="text"
                      [(ngModel)]="ratingScore"
                      placeholder="0.0 – 10.0"
                      class="rating-input-field"
                      (keydown.enter)="submitRating(item.tmdbId)"
                    />
                    <button class="submit-rating-btn" (click)="submitRating(item.tmdbId)">
                      Submit
                    </button>
                  </div>
                </div>

                <!-- Eigene Bewertung als Badge -->
                <div class="own-rating-tag" *ngIf="getRating(item.tmdbId) !== null">
                  <span class="star-icon">★</span>
                  {{ getRating(item.tmdbId) | number:'1.1-1' }}
                </div>
              </div>

              <!-- Titel -->
              <p class="card-title">{{ item.title }} ({{ item.releaseYear }})</p>

              <!-- Externe Ratings -->
              <div class="ratings-container">
                <div class="imdb-rating">
                  <img src="/assets/images/imdb-logo.png" alt="IMDb" class="rating-icon imdb-rating-icon" />
                  {{
                    item.imdbRating != null
                      ? (item.imdbRating | number:'1.1-1')
                      : 'N/A'
                  }}
                </div>
                <div class="rt-rating">
                  <img src="/assets/images/rt-logo-cf.png" alt="Rotten Tomatoes" class="rating-icon rt-rating-icon" />
                  <ng-container *ngIf="item.rtRating != null; else homeRtNA">
                    {{ item.rtRating | number:'1.0-0' }}%
                  </ng-container>
                  <ng-template #homeRtNA>N/A</ng-template>
                </div>
              </div>
            </div>
          </ng-container>

          <!-- Ladezustand -->
          <ng-template #loadingState>
            <div *ngIf="category.isLoading" class="loading-placeholder">
              <div class="skeleton-card" *ngFor="let _ of placeholderItems"></div>
            </div>
          </ng-template>
        </div>
      </div>

      <button
        class="slider-arrow right-arrow"
        *ngIf="category.id !== 'watchlist' || canScrollRight(category.id)"
        (click)="scrollRight(category.id)"
      >
        <svg viewBox="0 0 24 24" width="32" height="32" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            d="M8.5 4.5L15.5 11.5L8.5 18.5"
            stroke="#fff"
            stroke-width="2.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </button>
    </div>
  </section>

</div>

// frontend/src/features/Home.tsx

import React, { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Content } from '../types/content';
import { getTrending, getTopRated, getNewReleases } from '../api/contentApi';
import { useWatchlist } from "../hooks/useWatchlist";
import { useRatings } from '../hooks/useRatings';
import { useAuth } from '../hooks/useAuth';
import styles from './Home.module.scss';

interface Category {
  id: string;
  title: string;
  items: Content[];
  isLoading: boolean;
}

const Home: React.FC = () => {
    
  const navigate = useNavigate();
  const auth = useAuth();
  const loggedIn = auth.isLoggedIn();

  const { getWatchlist, addToWatchlist, removeFromWatchlist, isInWatchlist } = useWatchlist();
  const { fetchUserRatings, rateContent, getRating } = useRatings();

  const [categories, setCategories] = useState<Category[]>([
    { id: 'trending', title: 'Trending Now', items: [], isLoading: false },
    { id: 'top-rated', title: 'Top Rated', items: [], isLoading: false },
    { id: 'new-releases', title: 'New Releases', items: [], isLoading: false },
    { id: 'watchlist', title: 'My Watchlist', items: [], isLoading: false }
  ]);

  const placeholderItems = Array.from({ length: 5 });

  const [scrollLeftState, setScrollLeftState] = useState<Record<string, boolean>>({});
  const ratingInputRef = useRef<HTMLInputElement>(null);
  const [selectedContentId, setSelectedContentId] = useState<string | null>(null);
  const [selectedCategoryId, setSelectedCategoryId] = useState<string | null>(null);
  const [ratingScore, setRatingScore] = useState('');
  const [isRatingSubmitted, setIsRatingSubmitted] = useState(false);

  const setLoading = (index: number, value: boolean) => {
    setCategories(prev => {
      const updated = [...prev];
      if (updated[index]) updated[index] = { ...updated[index], isLoading: value };
      return updated;
    });
  };

  const setItems = (index: number, items: Content[]) => {
    setCategories(prev => {
      const updated = [...prev];
      if (updated[index]) updated[index] = { ...updated[index], items, isLoading: false };
      return updated;
    });
  };

  const updateScrollState = (categoryId: string) => {
    const el = document.getElementById(categoryId);
    setScrollLeftState(prev => ({ ...prev, [categoryId]: !!el && el.scrollLeft > 0 }));
  };

  const canScrollLeft = (categoryId: string) => !!scrollLeftState[categoryId];

  const canScrollRight = (categoryId: string) => {
    const el = document.getElementById(categoryId);
    if (!el) return false;
    return el.scrollWidth - el.clientWidth - el.scrollLeft > 10;
  };

  const scrollLeft = (categoryId: string) => {
    const el = document.getElementById(categoryId);
    if (el) {
      el.scrollBy({ left: -300, behavior: 'smooth' });
      setTimeout(() => updateScrollState(categoryId), 350);
    }
  };

  const scrollRight = (categoryId: string) => {
    const el = document.getElementById(categoryId);
    if (el) {
      el.scrollBy({ left: 300, behavior: 'smooth' });
      setTimeout(() => updateScrollState(categoryId), 350);
    }
  };

  const loadPublicCategories = async () => {
    setLoading(0, true);
    try {
      const data = await getTrending();
      setItems(0, data);
    } catch (err) {
      console.error('Failed to load trending', err);
      setLoading(0, false);
    }

    setLoading(1, true);
    try {
      const data = await getTopRated();
      setItems(1, data);
    } catch (err) {
      console.error('Failed to load top rated', err);
      setLoading(1, false);
    }

    setLoading(2, true);
    try {
      const data = await getNewReleases();
      setItems(2, data);
    } catch (err) {
      console.error('Failed to load new releases', err);
      setLoading(2, false);
    }
  };

  const loadCategories = async () => {
    await loadPublicCategories();
    setLoading(3, true);
    try {
      const data = await getWatchlist();
      setItems(3, data as unknown as Content[]);
    } catch (err) {
      console.error('Failed to load watchlist', err);
      setLoading(3, false);
    }
  };

  useEffect(() => {
    fetchUserRatings().catch(err => console.error('Failed to fetch ratings', err));
    if (loggedIn) {
      loadCategories();
    } else {
      loadPublicCategories();
    }
  }, [loggedIn]);

  useEffect(() => {
    categories.forEach(cat => updateScrollState(cat.id));
  }, [categories]);

  const toggleWatchlist = async (contentId: string, type: 'movie' | 'tv') => {
    if (!loggedIn) {
      navigate('/auth/login');
      return;
    }
    try {
      if (isInWatchlist(contentId)) {
        await removeFromWatchlist(contentId);
      } else {
        await addToWatchlist({ id: contentId, type });
      }
      const data = await getWatchlist();
      setItems(3, data as unknown as Content[]);
    } catch (err) {
      console.error(err);
    }
  };

  const startRating = (categoryId: string, contentId: string) => {
    if (!loggedIn) {
      navigate('/auth/login');
      return;
    }
    setSelectedCategoryId(categoryId);
    setSelectedContentId(contentId);
    setRatingScore('');
    setIsRatingSubmitted(false);
    setTimeout(() => ratingInputRef.current?.focus(), 0);
  };

  const stopRating = () => {
    setSelectedCategoryId(null);
    setSelectedContentId(null);
    setRatingScore('');
    setIsRatingSubmitted(false);
  };

  const submitRating = async (tmdbId: string) => {
    const score = parseFloat(ratingScore);
    if (isNaN(score) || score < 0 || score > 10) {
      console.error('Invalid rating');
      return;
    }
    if (!loggedIn) {
      navigate('/auth/login');
      return;
    }
    try {
      await rateContent(tmdbId, score);
      setIsRatingSubmitted(true);
      await fetchUserRatings();
      setTimeout(() => stopRating(), 500);
    } catch (err) {
      console.error('Failed to set rating', err);
    }
  };

  return (
    <div className={styles['home-container']}>
      <section className={styles['hero-section']}>
        <div className={styles['hero-content']}>
          <h1>Your personal streaming companion</h1>
          <p>rate, discover and keep track of what you love</p>
        </div>
      </section>

      {categories.map((category) => (
        <section key={category.id} className={styles['category-section']}>
          <h2>{category.title}</h2>
          <div className={styles['slider-container']}>
            {canScrollLeft(category.id) && (
              <button
                className={`${styles['slider-arrow']} ${styles['left-arrow']}`}
                onClick={() => scrollLeft(category.id)}
              >
                <svg viewBox="0 0 24 24" width="32" height="32" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M15.5 19.5L8.5 12.5L15.5 5.5" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </button>
            )}

            <div
              className={styles['scroll-container']}
              id={category.id}
              onScroll={() => updateScrollState(category.id)}
            >
              <div className={styles['content-list']}>
                {category.items.length > 0 ? (
                  category.items.map(item => (
                    <Link
                      to={`/movies/${item.tmdbId}`}
                      key={item.tmdbId}
                      className={styles['content-card']}
                      onMouseLeave={stopRating}
                      onClick={e => {
                        if (selectedContentId) {
                          e.preventDefault();
                        }
                      }}
                    >
                      <div
                        className={styles['card-image']}
                        style={{ backgroundImage: `url(${item.poster || 'https://placehold.co/200x300'})` }}
                      >
                        <button
                          className={styles['add-btn']}
                          onClick={e => {
                            e.preventDefault();
                            toggleWatchlist(item.tmdbId, item.type);
                          }}
                        >
                          <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2">
                            <path
                              d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"
                              fill={isInWatchlist(item.tmdbId) ? 'currentColor' : 'none'}
                            />
                          </svg>
                        </button>
                        <button
                          className={styles['rating-btn']}
                          onClick={e => {
                            e.preventDefault();
                            startRating(category.id, item.tmdbId);
                          }}
                        >
                          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
                            <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z" />
                          </svg>
                        </button>

                        {selectedCategoryId === category.id &&
                          selectedContentId === item.tmdbId &&
                          !isRatingSubmitted && (
                            <>
                              <div className={styles['rating-overlay']} />
                              <div className={styles['rating-input-container']}>
                                <div className={styles['rating-card']}>
                                  <button
                                    className={styles['close-btn']}
                                    onClick={e => {
                                      e.preventDefault();
                                      stopRating();
                                    }}
                                  >
                                    ✕
                                  </button>
                                  <h3>Rate “{item.title}”</h3>
                                  <input
                                    ref={ratingInputRef}
                                    type="text"
                                    value={ratingScore}
                                    placeholder="0.0 – 10.0"
                                    className={styles['rating-input-field']}
                                    onChange={e => setRatingScore(e.target.value)}
                                    onKeyDown={e => {
                                      if (e.key === 'Enter') {
                                        e.preventDefault();
                                        submitRating(item.tmdbId);
                                      }
                                    }}
                                  />
                                  <button
                                    className={styles['submit-rating-btn']}
                                    onClick={e => {
                                      e.preventDefault();
                                      submitRating(item.tmdbId);
                                    }}
                                  >
                                    Submit
                                  </button>
                                </div>
                              </div>
                            </>
                          )}

                        {getRating(item.tmdbId) != null && (
                          <div className={styles['own-rating-tag']}>
                            <span className={styles['star-icon']}>★</span>
                            {getRating(item.tmdbId)?.toFixed(1)}
                          </div>
                        )}
                      </div>

                      <p className={styles['card-title']}>
                        {item.title} ({item.releaseYear})
                      </p>

                      <div className={styles['ratings-container']}>
                        <div className={styles['imdb-rating']}>
                          <img
                            src="/assets/images/imdb-logo.png"
                            alt="IMDb"
                            className={styles['rating-icon']}
                          />
                          {item.imdbRating != null ? item.imdbRating.toFixed(1) : 'N/A'}
                        </div>
                        <div className={styles['rt-rating']}>
                          <img
                            src="/assets/images/rt-logo-cf.png"
                            alt="Rotten Tomatoes"
                            className={styles['rating-icon']}
                          />
                          {item.rtRating != null ? `${Math.round(item.rtRating)}%` : 'N/A'}
                        </div>
                      </div>
                    </Link>
                  ))
                ) : category.isLoading ? (
                  <div className={styles['loading-placeholder']}>
                    {placeholderItems.map((_, i) => (
                      <div key={i} className={styles['skeleton-card']} />
                    ))}
                  </div>
                ) : null}
              </div>
            </div>

            {(category.id !== 'watchlist' || canScrollRight(category.id)) && (
              <button
                className={`${styles['slider-arrow']} ${styles['right-arrow']}`}
                onClick={() => scrollRight(category.id)}
              >
                <svg viewBox="0 0 24 24" width="32" height="32" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M8.5 4.5L15.5 11.5L8.5 18.5" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </button>
            )}
          </div>
        </section>
      ))}
    </div>
  );
};
export default Home;
