// frontend/src/features/SeriesDetail/SeriesDetail.tsx
import React from "react";
import { useParams } from "react-router-dom";
import { useSeriesDetail } from "../../hooks/useSeriesDetail";
import styles from "./SeriesDetail.module.scss";
import { providerLogoMap } from "../../constants/providers";

const SeriesDetail: React.FC = () => {
  const { id } = useParams();
  const {
    series,
    isLoading,
    isInWL,
    userRating,
    selectedContentId,
    ratingScore,
    setRatingScore,
    isRatingSubmitted,
    toggleWatchlist,
    onClickRateButton,
    submitRating,
    cancelRating,
  } = useSeriesDetail(id);

  const getKnownProviders = (providers?: string[]) =>
    (providers || []).filter((p) => providerLogoMap[p]);

  const getProviderLogoPath = (provider: string) =>
    providerLogoMap[provider]
      ? `/assets/images/providers/${providerLogoMap[provider]}`
      : null;

  if (isLoading) return <div className={styles.loader}>Lade …</div>;
  if (!series) return <div className={styles.loader}>Serie nicht gefunden.</div>;

  return (
    <div className={styles.seriesDetailContainer}>
      <header className={styles.seriesHeader}>
        <h1 className={styles.seriesTitle}>
          {series.title}
          <span className={styles.seriesYear}>({series.releaseYear})</span>
        </h1>
      </header>

      <div className={styles.seriesContent}>
        <div className={styles.posterWrapper}>
          {/* Watchlist Button */}
          <button className={styles.addBtn} onClick={toggleWatchlist}>
            {!isInWL ? (
              <svg viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" fill="none" strokeWidth="2">
                <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
              </svg>
            ) : (
              <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
                <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
              </svg>
            )}
          </button>

          {/* Rating Button */}
          <button className={styles.ratingBtn} onClick={onClickRateButton}>
            <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
              <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 
                       9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/>
            </svg>
          </button>

          <img
            src={series.poster || "https://placehold.co/200x300"}
            alt={series.title}
            className={styles.seriesPoster}
          />

          {selectedContentId === series.tmdbId && !isRatingSubmitted && (
            <>
              <div className={styles.ratingOverlay} onClick={cancelRating}></div>
              <div className={styles.ratingInputContainer}>
                <div className={styles.ratingCard}>
                  <button className={styles.closeBtn} onClick={cancelRating}>✕</button>
                  <h3>Rate “{series.title}”</h3>
                  <input
                    type="text"
                    value={ratingScore}
                    onChange={(e) => setRatingScore(e.target.value)}
                    placeholder="0.0 – 10.0"
                    onKeyDown={(e) => e.key === "Enter" && submitRating()}
                    className={styles.ratingInputField}
                  />
                  <button className={styles.submitRatingBtn} onClick={submitRating}>
                    Submit
                  </button>
                </div>
              </div>
            </>
          )}
        </div>

        <div className={styles.detailsWrapper}>
          {/* External Ratings */}
          <div className={styles.ratingsWrapper}>
            <div className={styles.ratingBlock}>
              <img src="/assets/images/imdb-logo.png" alt="IMDb" className={styles.ratingIcon} />
              <span className={styles.ratingValue}>
                {series.imdbRating != null ? series.imdbRating.toFixed(1) : "–"}
              </span>
            </div>
            <div className={styles.ratingBlock}>
              <img src="/assets/images/rt-logo-cf.png" alt="RT" className={styles.ratingIcon} />
              <span className={styles.ratingValue}>
                {series.rtRating != null ? `${series.rtRating}%` : "–"}
              </span>
            </div>
            {userRating != null && (
              <div className={styles.ownRatingTag}>
                <span className={styles.starIcon}>★</span>
                {userRating.toFixed(1)}
              </div>
            )}
          </div>

          {/* Genres */}
          <div className={styles.genres}>
            {(series.genres || []).map((g) => (
              <span key={g} className={styles.genrePill}>{g}</span>
            ))}
          </div>

          {/* Providers */}
          {getKnownProviders(series.providers).length > 0 && (
            <section className={styles.providers}>
              {getKnownProviders(series.providers).map((p) => {
                const logo = getProviderLogoPath(p);
                return logo ? (
                  <img key={p} src={logo} alt={p} className={styles.providerLogo} />
                ) : null;
              })}
            </section>
          )}

          {/* Overview */}
          <section className={styles.overview}>
            <h2>Handlung</h2>
            <p>{series.overview || "Keine Beschreibung vorhanden."}</p>
          </section>

          {/* Cast */}
          {series.cast && series.cast.length > 0 && (
            <section className={styles.castSection}>
              <h2>Hauptbesetzung</h2>
              <div className={styles.castList}>
                {series.cast.map((actor) => (
                  <div key={actor.name} className={styles.castItem}>
                    <div className={styles.castImageWrapper}>
                      <img src={actor.profilePathUrl} alt={actor.name} />
                    </div>
                    <div className={styles.castInfo}>
                      <span className={styles.castName}>{actor.name}</span>
                      <span className={styles.castChar}>{actor.character}</span>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}
        </div>
      </div>
    </div>
  );
};

export default SeriesDetail;

// frontend/src/app/features/series-detail/series-detail.component.ts
import { Component, OnInit }           from '@angular/core';
import { CommonModule }                from '@angular/common';
import { ActivatedRoute, Router }              from '@angular/router';
import { ContentService }              from '../../core/services/content.service';
import { Content }                     from '../../interfaces/content.interface';
import { WatchlistService } from '../../core/services/watchlist.service';
import { RatingsService } from '../../core/services/ratings.service';
import { AuthService } from '../../core/services/auth.service';
import { FormsModule } from '@angular/forms';
import { providerLogoMap } from '../../shared/provider-logos';
import { debugError } from '../../core/utils/logger';

@Component({
  selector: 'app-series-detail',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './series-detail.component.html',
  styleUrls: ['./series-detail.component.scss']
})
export class SeriesDetailComponent implements OnInit {
  series: Content | null = null;
  isLoading = true;
  isInWL                        = false;

  // Rate‐Overlay
  selectedContentId: string | null = null;
  ratingScore            = '';
  isRatingSubmitted      = false;

  // Eigenes Rating
  userRating: number | null = null;

  readonly providerLogoMap = providerLogoMap;

  constructor(
    private route: ActivatedRoute,
    private contentService: ContentService,
    private router: Router,
    private watchlist: WatchlistService,
    private ratings: RatingsService,
    private auth: AuthService
  ) {}

  ngOnInit() {
    const tmdbId = this.route.snapshot.paramMap.get('id')!;
    this.contentService.getSeriesDetails(tmdbId).subscribe({
      next: s => {
        this.series = s;
        this.isLoading = false;
        // Watchlist‐Cache laden
        this.watchlist.getWatchlist().subscribe(list =>
          this.isInWL = list.some(c => c.tmdbId === tmdbId)
        );
        // Rating‐Cache laden
        this.ratings.fetchUserRatings().subscribe(() =>
          this.userRating = this.ratings.getRating(tmdbId)
        );
      },
      error: () => this.isLoading = false
    });
  }
  toggleWatchlist() {
    this.auth.isLoggedIn().subscribe(loggedIn => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
        return;
      }
      if (!this.series) return;
      const id = this.series.tmdbId;
      const op = this.isInWL
        ? this.watchlist.removeFromWatchlist(id)
        : this.watchlist.addToWatchlist(id, 'tv');
      op.subscribe({
        next: res => {
          if (res !== null && res !== undefined) {
            this.isInWL = !this.isInWL;
          }
        },
        error: err => debugError('Failed to toggle watchlist', err),
      });
    });
  }

  onClickRateButton() {
    this.auth.isLoggedIn().subscribe(loggedIn => {
      if (!loggedIn) {
        this.router.navigate(['/auth/login']);
      } else if (this.series) {
        this.selectedContentId = this.series.tmdbId;
        this.ratingScore      = '';
        this.isRatingSubmitted = false;
      }
    });
  }

  submitRating() {
    if (!this.series) return;
    const score = parseFloat(this.ratingScore);
    if (isNaN(score) || score < 0 || score > 10) {
      alert('Score must be between 0.0 and 10.0');
      return;
    }
    this.ratings.rateContent(this.series.tmdbId, score).subscribe({
      next: () => {
        this.isRatingSubmitted = true;
        this.ratings.fetchUserRatings().subscribe(() =>
          this.userRating = this.ratings.getRating(this.series!.tmdbId)
        );
        setTimeout(() => this.selectedContentId = null, 500);
      },
      error: err => debugError('Failed to set rating', err)
    });
  }

  cancelRating() {
    this.selectedContentId = null;
    this.ratingScore      = '';
    this.isRatingSubmitted = false;
  }

  getKnownProviders(providers: string[] | undefined): string[] {
    return (providers || []).filter(p => this.providerLogoMap[p]);
  }

  getProviderLogoPath(provider: string): string | null {
    const file = this.providerLogoMap[provider];
    return file ? '/assets/images/providers/' + file : null;
  }
}
<ng-container *ngIf="isLoading">
  <div class="loader">Lade …</div>
</ng-container>

<ng-container *ngIf="!isLoading && series; else noSeries">
  <div class="series-detail-container">

    <header class="series-header">
      <h1 class="series-title">
        {{ series.title }}
        <span class="series-year">({{ series.releaseYear }})</span>
      </h1>
    </header>

    <div class="series-content">
      <div class="poster-wrapper">
        <!-- Add-Button oben links -->
        <button class="add-btn" (click)="toggleWatchlist(); $event.stopPropagation()">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2">
            <path *ngIf="!isInWL" d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
            <path *ngIf="isInWL" d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" fill="currentColor" stroke="none"/>
          </svg>
        </button>

        <!-- Rate-Button direkt darunter -->
        <button class="rating-btn" (click)="onClickRateButton(); $event.stopPropagation()">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
            <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2
                     9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/>
          </svg>
        </button>

        <img
          [src]="series.poster || 'https://placehold.co/200x300'"
          [alt]="series.title"
          class="series-poster"
        />

        <!-- Rating-Overlay -->
        <div
          class="rating-overlay"
          *ngIf="selectedContentId === series.tmdbId && !isRatingSubmitted"
          (click)="cancelRating()"
        ></div>

        <!-- Rating-Card -->
        <div
          class="rating-input-container"
          *ngIf="selectedContentId === series.tmdbId && !isRatingSubmitted"
        >
          <div class="rating-card">
            <button class="close-btn" (click)="cancelRating()">✕</button>
            <h3>Rate “{{ series.title }}”</h3>
            <input
              #ratingInput
              type="text"
              [(ngModel)]="ratingScore"
              placeholder="0.0 – 10.0"
              (keydown.enter)="submitRating()"
              class="rating-input-field"
            />
            <button class="submit-rating-btn" (click)="submitRating()">
              Submit
            </button>
          </div>
        </div>
      </div>

      <div class="details-wrapper">
        <!-- External Ratings -->
        <div class="ratings-wrapper">
          <div class="rating-block">
            <img
              src="/assets/images/imdb-logo.png"
              alt="IMDb"
              class="rating-icon imdb-rating-icon"
            />
            <span class="rating-value">
              {{ series.imdbRating != null
                  ? (series.imdbRating | number:'1.1-1')
                  : '–' }}
            </span>
          </div>
          <div class="rating-block">
            <img
              src="/assets/images/rt-logo-cf.png"
              alt="Rotten Tomatoes"
              class="rating-icon rt-rating-icon"
            />
            <span class="rating-value">
              {{ series.rtRating != null
                  ? (series.rtRating + '%')
                  : '–' }}
            </span>
          </div>
          <div class="own-rating-tag" *ngIf="userRating != null">
          <span class="star-icon">★</span>
          {{ userRating | number:'1.1-1' }}
        </div>
        </div>

        <!-- Genres -->
        <div class="genres">
          <span class="genre-pill" *ngFor="let g of (series.genres || [])">
            {{ g }}
          </span>
        </div>

        <section class="providers" *ngIf="getKnownProviders(series.providers).length">
          <ng-container *ngFor="let p of getKnownProviders(series.providers)">
            <img
              *ngIf="getProviderLogoPath(p) as logo"
              [src]="logo"
              [alt]="p"
              class="provider-logo"
            />
          </ng-container>
        </section>

        <!-- Overview -->
        <section class="overview">
          <h2>Handlung</h2>
          <p>{{ series.overview || 'Keine Beschreibung vorhanden.' }}</p>
        </section>

        <!-- Cast -->
        <section class="cast-section" *ngIf="(series.cast || []).length > 0">
          <h2>Hauptbesetzung</h2>
          <div class="cast-list">
            <div class="cast-item" *ngFor="let actor of (series.cast || [])">
              <div class="cast-image-wrapper">
                <img
                  [src]="actor.profilePathUrl"
                  [alt]="actor.name"
                />
              </div>
              <div class="cast-info">
                <span class="cast-name">{{ actor.name }}</span>
                <span class="cast-char">{{ actor.character }}</span>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</ng-container>

<ng-template #noSeries>
  <div class="loader">Serie nicht gefunden.</div>
</ng-template>
